const RARITY = {
    COMMON: 'Common',
    FREE: 'Free',
    RARE: 'Rare',
    EPIC: 'Epic',
    LEGENDARY: 'Legendary',
  },
  TRIBE = {
    NONE: 0,
    BEAST: 1,
    TOTEM: 2,
    DEMON: 3,
    MURLOC: 4,
    PIRATE: 5,
    MECH: 6,
    UNDEAD: 7,
    DRAGON: 8,
  },
  CLASS = {
    DRUID: 0,
    HUNTER: 1,
    MAGE: 2,
    PALADIN: 3,
    PRIEST: 4,
    ROGUE: 5,
    SHAMAN: 6,
    WARLOCK: 7,
    WARRIOR: 8,
  },
  ATTRIBUTES = {
    CHARGE: 0,
    TAUNT: 1,
    DIVINE_SHIELD: 2,
    STEALTH: 3,
    WINDFURY: 4,
    ELUSIVE: 5,
    POISON: 6,
  },
  MINION_DATA = [
    // minion objects will have more data than this
    // these are just the baseline stats for each minion, before manipulation

    // DRUID
    {
      class: CLASS.DRUID,
      name: 'Keeper of the Grove',
      fileName: 'keeper_of_the_grove',
      description: '',
      stats: [4, 2, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,

      // [CHARGE, TAUNT, DIVINE_SHIELD, STEALTH, WINDFURY, ELUSIVE, POISON]
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.DRUID,
      name: 'Druid of the Claw',
      fileName: 'druid_of_the_claw',
      description: '',
      stats: [5, 4, 4],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.DRUID,
      name: 'Ancient of Lore',
      description: '',
      fileName: 'ancient_of_lore',
      stats: [7, 5, 5],
      rarity: RARITY.EPIC,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.DRUID,
      name: 'Ancient of War',
      description: '',
      fileName: 'ancient_of_war',
      stats: [7, 5, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.DRUID,
      name: 'Ironbark Protector',
      fileName: 'ironbark_protector',
      description: '',
      stats: [8, 8, 8],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      class: CLASS.DRUID,
      name: 'Cenarius',
      fileName: 'cenarius',
      description: '',
      stats: [9, 5, 8],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    // HUNTER
    {
      class: CLASS.HUNTER,
      name: 'Timber Wolf',
      fileName: 'timber_wolf',
      description: '',
      stats: [1, 1, 1],
      rarity: RARITY.FREE,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'Scavenging Hyena',
      fileName: 'scavenging_hyena',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'Starving Buzzard',
      fileName: 'starving_buzzard',
      description: '',
      stats: [2, 2, 1],
      rarity: RARITY.FREE,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'Houndmaster',
      fileName: 'houndmaster',
      description: '',
      stats: [4, 4, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'Tundra Rhino',
      fileName: 'tundra_rhino',
      description: '',
      stats: [5, 2, 5],
      rarity: RARITY.FREE,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'Savannah Highmane',
      fileName: 'savannah_highmane',
      description: '',
      stats: [6, 6, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.HUNTER,
      name: 'King Krush',
      fileName: 'king_krush',
      description: '',
      stats: [9, 8, 8],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.BEAST,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
    // MAGE
    {
      class: CLASS.MAGE,
      name: 'Mana Wyrm',
      fileName: 'mana_wyrm',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.MAGE,
      name: "Sorcerer's Apprentice",
      fileName: 'sorcerers_apprentice',
      description: '',
      stats: [2, 3, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.MAGE,
      name: 'Kirin Tor Mage',
      fileName: 'kirin_tor_mage',
      description: '',
      stats: [3, 4, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.MAGE,
      name: 'Ethereal Arcanist',
      fileName: 'ethereal_arcanist',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.MAGE,
      name: 'Water Elemental',
      fileName: 'water_elemental',
      description: '',
      stats: [4, 3, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.MAGE,
      name: 'Archmage Antonidas',
      fileName: 'archmage_antonidas',
      description: '',
      stats: [7, 5, 7],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    // PALADIN
    {
      class: CLASS.PALADIN,
      name: 'Argent Protector',
      fileName: 'argent_protector',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PALADIN,
      name: 'Aldor Peacekeeper',
      fileName: 'aldor_peacekeeper',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PALADIN,
      name: 'Guardian of Kings',
      fileName: 'guardian_of_kings',
      description: '',
      stats: [7, 5, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PALADIN,
      name: 'Tirion Fordring',
      fileName: 'tirion_fordring',
      description: '',
      stats: [8, 6, 6],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    // PRIEST
    {
      class: CLASS.PRIEST,
      name: 'Northshire Cleric',
      fileName: 'northshire_cleric',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Lightwell',
      fileName: 'lightwell',
      description: '',
      stats: [2, 0, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Auchenai Soulpriest',
      fileName: 'auchenai_soulpriest',
      description: '',
      stats: [4, 3, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Lightspawn',
      fileName: 'lightspawn',
      description: '',
      stats: [4, 0, 5],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Cabal Shadow Priest',
      fileName: 'cabal_shadow_priest',
      description: '',
      stats: [6, 4, 5],
      rarity: RARITY.EPIC,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Temple Enforcer',
      fileName: 'temple_enforcer',
      description: '',
      stats: [6, 6, 6],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.PRIEST,
      name: 'Prophet Velen',
      fileName: 'prophet_velen',
      description: '',
      stats: [7, 7, 7],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    // ROGUE
    {
      class: CLASS.ROGUE,
      name: 'Defias Ring Leader',
      fileName: 'defias_ring_leader',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.ROGUE,
      name: 'Patient Assassin',
      fileName: 'patient_assassin',
      description: '',
      stats: [2, 1, 1],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, true, false, false, true],
    },
    {
      class: CLASS.ROGUE,
      name: 'Edwin VanCleef',
      fileName: 'edwin_vancleef',
      description: '',
      stats: [3, 2, 2],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.ROGUE,
      name: 'SI:7 Agent',
      fileName: 'si7_agent',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.ROGUE,
      name: 'Master of Disguise',
      fileName: 'master_of_disguise',
      description: '',
      stats: [4, 4, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.ROGUE,
      name: 'Kidnapper',
      fileName: 'kidnapper',
      description: '',
      stats: [6, 5, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.UNDEAD,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    // SHAMAN
    {
      class: CLASS.SHAMAN,
      name: 'Dust Devil',
      fileName: 'dust_devil',
      description: '',
      stats: [1, 3, 1],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 2,
      attributes: [false, false, false, false, true, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Flametongue Totem',
      fileName: 'flametongue_totem',
      description: '',
      stats: [2, 0, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.TOTEM,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Mana Tide Totem',
      fileName: 'mana_tide_totem',
      description: '',
      stats: [3, 0, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.TOTEM,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Unbound Elemental',
      fileName: 'unbound_elemental',
      description: '',
      stats: [3, 2, 4],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Windspeaker',
      fileName: 'windspeaker',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Earth Elemental',
      fileName: 'earth_elemental',
      description: '',
      stats: [5, 7, 8],
      rarity: RARITY.EPIC,
      tribe: TRIBE.NONE,
      overload: 3,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: 'Fire Elemental',
      fileName: 'fire_elemental',
      description: '',
      stats: [6, 6, 5],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.SHAMAN,
      name: "Al'Akir the Windlord",
      fileName: 'alakir_the_windlord',
      description: '',
      stats: [8, 3, 5],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, true, true, false, true, false, false],
    },
    // WARLOCK
    {
      class: CLASS.WARLOCK,
      name: 'Blood Imp',
      fileName: 'blood_imp',
      description: '',
      stats: [1, 0, 1],
      rarity: RARITY.COMMON,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, true, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Flame Imp',
      fileName: 'flame_imp',
      description: '',
      stats: [1, 3, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Voidwalker',
      fileName: 'voidwalker',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Felstalker',
      fileName: 'felstalker',
      description: '',
      stats: [2, 4, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Felguard',
      fileName: 'felguard',
      description: '',
      stats: [3, 3, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Void Terror',
      fileName: 'void_terror',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Pit Lord',
      fileName: 'pit_lord',
      description: '',
      stats: [4, 5, 6],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Summoning Portal',
      fileName: 'summoning_portal',
      description: '',
      stats: [4, 0, 4],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Doomguard',
      fileName: 'doomguard',
      description: '',
      stats: [5, 5, 7],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Dread Infernal',
      fileName: 'dread_infernal',
      description: '',
      stats: [6, 6, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARLOCK,
      name: 'Lord Jaraxxus',
      fileName: 'lord_jaraxxus',
      description: '',
      stats: [9, 3, 15],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    // WARRIOR
    {
      class: CLASS.WARRIOR,
      name: 'Armorsmith',
      fileName: 'armorsmith',
      description: '',
      stats: [2, 1, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: 'Cruel Taskmaster',
      fileName: 'cruel_taskmaster',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: 'Frothing Berserker',
      fileName: 'frothing_berserker',
      description: '',
      stats: [3, 2, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: 'Warsong Commander',
      fileName: 'warsong_commander',
      description: '',
      stats: [3, 2, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: 'Arathi Weaponsmith',
      fileName: 'arathi_weaponsmith',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: "Kor'kron Elite",
      fileName: 'korkron_elite',
      description: '',
      stats: [4, 4, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
    {
      class: CLASS.WARRIOR,
      name: 'Grommash Hellscream',
      fileName: 'grommash_hellscream',
      description: '',
      stats: [8, 4, 9],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
  ]

module.exports = {
  ATTRIBUTES,
  MINION_DATA,
}
