const Enum = require('enum')

const CLASS = new Enum([
  DRUID,
  HUNTER,
  MAGE,
  PALADIN,
  PRIEST,
  ROGUE,
  SHAMAN,
  WARLOCK,
  WARRIOR,
])

const TYPE = new Enum([
  SPELL,
  CHOOSE_ONE,
  BATTLECRY,
  DEATHRATTLE,
  AURA,
  GENERIC, // not any of the others; shouldn't trigger any additional effects
])

const RARITY = {
    COMMON: 'Common',
    FREE: 'Free',
    RARE: 'Rare',
    EPIC: 'Epic',
    LEGENDARY: 'Legendary',
  },
  EFFECT_DATA = {
    // effect objects will have more data than this
    // these are just the baseline values

    // DRUID
    INNERVATE: {
      type: TYPE.SPELL.value,
      fileName: 'innervate', // for card displays on spells and "choose one"
      class: CLASS.DRUID.value,
      name: 'Innervate',
      baseDescription: 'Gain 2 Mana Crystals this turn only.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0], // doesn't apply when not affected by spellpower
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MOONFIRE: {
      type: TYPE.SPELL.value,
      fileName: 'moonfire',
      class: CLASS.DRUID.value,
      name: 'Moonfire',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    CLAW: {
      type: TYPE.SPELL.value,
      fileName: 'claw',
      class: CLASS.DRUID.value,
      name: 'Claw',
      baseDescription: 'Give your hero +2 Attack this turn. Gain 2 Armor.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    NATURALIZE: {
      type: TYPE.SPELL.value,
      fileName: 'naturalize',
      class: CLASS.DRUID.value,
      name: 'Naturalize',
      baseDescription: 'Destroy a minion. Your opponent draws 2cards.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SAVAGERY: {
      type: TYPE.SPELL.value,
      fileName: 'savagery',
      class: CLASS.DRUID.value,
      name: 'Savagery',
      baseDescription: "Deal damage equal to your hero's Attack to a minion.",
      rarity: RARITY.RARE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MARK_OF_THE_WILD: {
      type: TYPE.SPELL.value,
      fileName: 'mark_of_the_wild',
      class: CLASS.DRUID.value,
      name: 'Mark of the Wild',
      baseDescription:
        'Give a minion <b>Taunt</b> and +2/+2. <i>(+2 Attack/+2 Health)</i>',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    POWER_OF_THE_WILD: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'power_of_the_wild',
      class: CLASS.DRUID.value,
      name: 'Power of the Wild',
      baseDescription:
        '<b>Choose One</b> - Give your minions +1/+1; or Summon a 3/2 Panther.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    POWER_OF_THE_WILD_LEADER_OF_THE_PACK: {
      type: TYPE.SPELL.value,
      fileName: 'power_of_the_wild_leader_of_the_pack',
      class: CLASS.DRUID.value,
      name: 'Leader of the Pack',
      baseDescription: 'Give your minions +1/+1.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    POWER_OF_THE_WILD_SUMMON_A_PANTHER: {
      type: TYPE.SPELL.value,
      fileName: 'power_of_the_wild_summon_a_panther',
      class: CLASS.DRUID.value,
      name: 'Summon a Panther',
      baseDescription: 'Summon a 3/2 Panther.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    WILD_GROWTH: {
      type: TYPE.SPELL.value,
      fileName: 'wild_growth',
      class: CLASS.DRUID.value,
      name: 'Wild Growth',
      baseDescription: 'Gain an empty Mana Crystal.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    WRATH: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'wrath',
      class: CLASS.DRUID.value,
      name: 'Wrath',
      baseDescription:
        '<b>Choose One</b> - Deal {amount0} damage to a minion; or {amount1} damage and draw a card.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [3, 1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    WRATH_NATURES_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'wrath_natures_wrath',
      class: CLASS.DRUID.value,
      name: "Nature's Wrath",
      baseDescription: 'Deal {amount0} damage to a minion. Draw a card.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    WRATH_SOLAR_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'wrath_solar_wrath',
      class: CLASS.DRUID.value,
      name: 'Solar Wrath',
      baseDescription: 'Deal {amount0} damage to a minion.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    HEALING_TOUCH: {
      type: TYPE.SPELL.value,
      fileName: 'healing_touch',
      class: CLASS.DRUID.value,
      name: 'Healing Touch',
      baseDescription: 'Restore {amount0} Health.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [8],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MARK_OF_NATURE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'mark_of_nature',
      class: CLASS.DRUID.value,
      name: 'Mark of Nature',
      baseDescription:
        '<b>Choose One</b> - Give a minion +4 Attack; or +4 Health and <b>Taunt</b>.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MARK_OF_NATURE_TIGERS_FURY: {
      type: TYPE.SPELL.value,
      fileName: 'mark_of_nature_tigers_fury',
      class: CLASS.DRUID.value,
      name: "Tiger's Fury",
      baseDescription: 'Give a minion +4 Attack.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    MARK_OF_NATURE_THICK_HIDE: {
      type: TYPE.SPELL.value,
      fileName: 'mark_of_nature_thick_hide',
      class: CLASS.DRUID.value,
      name: 'Thick Hide',
      baseDescription: 'Give a minion +4 Health and <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    SAVAGE_ROAR: {
      type: TYPE.SPELL.value,
      fileName: 'savage_roar',
      class: CLASS.DRUID.value,
      name: 'Savage Roar',
      baseDescription: 'Give your characters +2 Attack this turn.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    BITE: {
      type: TYPE.SPELL.value,
      fileName: 'bite',
      class: CLASS.DRUID.value,
      name: 'Bite',
      baseDescription: 'Give your hero +4 Attack this turn. Gain 4 Armor.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SOUL_OF_THE_FOREST: {
      type: TYPE.SPELL.value,
      fileName: 'soul_of_the_forest',
      class: CLASS.DRUID.value,
      name: 'Soul of the Forest',
      baseDescription:
        'Give your minions "<b>Deathrattle<\b>: Summon a 2/2 Treant."',
      rarity: RARITY.COMMON,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SWIPE: {
      type: TYPE.SPELL.value,
      fileName: 'swipe',
      class: CLASS.DRUID.value,
      name: 'Swipe',
      baseDescription:
        'Deal {amount0} damage to an enemy and {amount1} damage  to all other enemies.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [4, 1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    NOURISH: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'nourish',
      class: CLASS.DRUID.value,
      name: 'Nourish',
      baseDescription:
        '<b>Choose One</b> - Gain 2 Mana Crystal; or Draw 3 cards.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    NOURISH_ENRICH: {
      type: TYPE.SPELL.value,
      fileName: 'nourish_enrich',
      class: CLASS.DRUID.value,
      name: 'Enrich',
      baseDescription: 'Draw 3 cards.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    NOURISH_RAMPANT_GROWTH: {
      type: TYPE.SPELL.value,
      fileName: 'nourish_rampant_growth',
      class: CLASS.DRUID.value,
      name: 'Rampant Growth',
      baseDescription: 'Gain 2 Mana Crystals.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    STARFALL: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'starfall',
      class: CLASS.DRUID.value,
      name: 'Starfall',
      baseDescription:
        '<b>Choose One</b> - Deal {amount0} damage to a minion; or {amount1} damage to all enemy minions.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: [5, 2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    STARFALL_STARLORD: {
      type: TYPE.SPELL.value,
      fileName: 'starfall_starlord',
      class: CLASS.DRUID.value,
      name: 'Starlord',
      baseDescription: 'Deal {amount0} damage to a minion.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    STARFALL_STELLAR_DRIFT: {
      type: TYPE.SPELL.value,
      fileName: 'starfall_stellar_drift',
      class: CLASS.DRUID.value,
      name: 'Stellar Drift',
      baseDescription: 'Deal {amount0} damage to all enemy minions.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    FORCE_OF_NATURE: {
      type: TYPE.SPELL.value,
      fileName: 'force_of_nature',
      class: CLASS.DRUID.value,
      name: 'Force of Nature',
      baseDescription:
        'Summon three 2/2 Treants with <b>Charge</b> that die at the end of the turn.',
      rarity: RARITY.EPIC,
      cost: 6,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    STARFIRE: {
      type: TYPE.SPELL.value,
      fileName: 'starfire',
      class: CLASS.DRUID.value,
      name: 'Starfire',
      baseDescription: 'Deal {amount0} damage. Draw a card.',
      rarity: RARITY.FREE,
      cost: 6,
      amount: [5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    // HUNTER
    HUNTERS_MARK: {
      type: TYPE.SPELL.value,
      fileName: 'hunters_mark',
      class: CLASS.HUNTER.value,
      name: "Hunter's Mark",
      baseDescription: "Change a minion's Health to 1.",
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    ARCANE_SHOT: {
      type: TYPE.SPELL.value,
      fileName: 'arcane_shot',
      class: CLASS.HUNTER.value,
      name: 'Arcane Shot',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BESTIAL_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'bestial_wrath',
      class: CLASS.HUNTER.value,
      name: 'Bestial Wrath',
      baseDescription: 'Give a Beast +2 Attack and <b>Immune</b> this turn.',
      rarity: RARITY.EPIC,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    FLARE: {
      type: TYPE.SPELL.value,
      fileName: 'flare',
      class: CLASS.HUNTER.value,
      name: 'Flare',
      baseDescription:
        'All minions lose <b>Stealth</b>.\nDestroy all enemy\n<b>Secrets</b>. Draw a card.',
      rarity: RARITY.RARE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    TRACKING: {
      type: TYPE.SPELL.value,
      fileName: 'tracking',
      class: CLASS.HUNTER.value,
      name: 'Tracking',
      baseDescription:
        'Look at the top 3 cards of your deck. Draw one and discard the others.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    EXPLOSIVE_TRAP: {
      type: TYPE.SPELL.value,
      fileName: 'explosive_trap',
      class: CLASS.HUNTER.value,
      name: 'Explosive Trap',
      baseDescription:
        '<b>Secret</b>: When your hero is attacked, deal {amount0} damage to all enemies.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    FREEZING_TRAP: {
      type: TYPE.SPELL.value,
      fileName: 'freezing_trap',
      class: CLASS.HUNTER.value,
      name: 'Freezing Trap',
      baseDescription:
        "<b>Secret</b>: When an enemy minion attacks, return it to its owner's hand. It costs (2) more.",
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MISDIRECTION: {
      type: TYPE.SPELL.value,
      fileName: 'misdirection',
      class: CLASS.HUNTER.value,
      name: 'Misdirection',
      baseDescription:
        '<b>Secret</b>: When an enemy attacks your hero, instead it attacks another random character.',
      rarity: RARITY.RARE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SNAKE_TRAP: {
      type: TYPE.SPELL.value,
      fileName: 'snake_trap',
      class: CLASS.HUNTER.value,
      name: 'Snake Trap',
      baseDescription:
        '<b>Secret</b>: When one of your minions is attacked, summon three 1/1 Snakes.',
      rarity: RARITY.EPIC,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SNIPE: {
      type: TYPE.SPELL.value,
      fileName: 'snipe',
      class: CLASS.HUNTER.value,
      name: 'Snipe',
      baseDescription:
        '<b>Secret</b>: After your opponent plays a minion, deal {amount0} damage to it.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ANIMAL_COMPANION: {
      type: TYPE.SPELL.value,
      fileName: 'animal_companion',
      class: CLASS.HUNTER.value,
      name: 'Animal Companion',
      baseDescription: 'Summon a random Beast Companion.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    DEADLY_SHOT: {
      type: TYPE.SPELL.value,
      fileName: 'deadly_shot',
      class: CLASS.HUNTER.value,
      name: 'Deadly Shot',
      baseDescription: 'Destroy a random enemy minion.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    KILL_COMMAND: {
      type: TYPE.SPELL.value,
      fileName: 'kill_command',
      class: CLASS.HUNTER.value,
      name: 'Kill Command',
      baseDescription:
        'Deal {amount0} damage. If you control a Beast, deal {amount1} damage instead.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [3, 5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    UNLEASH_THE_HOUNDS: {
      type: TYPE.SPELL.value,
      fileName: 'unleash_the_hounds',
      class: CLASS.HUNTER.value,
      name: 'Unleash the Hounds',
      baseDescription:
        'For each enemy minion, summon a 1/1 Hound with <b>Charge</b>.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MULTI_SHOT: {
      type: TYPE.SPELL.value,
      fileName: 'multi_shot',
      class: CLASS.HUNTER.value,
      name: 'Multi-Shot',
      baseDescription: 'Deal {amount0} damage to two random enemy  minions.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    EXPLOSIVE_SHOT: {
      type: TYPE.SPELL.value,
      fileName: 'explosive_shot',
      class: CLASS.HUNTER.value,
      name: 'Explosive Shot',
      baseDescription:
        'Deal {amount0} damage to a minion and {amount1} damage to adjacent ones.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: [5, 2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    // MAGE
    ARCANE_MISSILES: {
      type: TYPE.SPELL.value,
      fileName: 'arcane_missiles',
      class: CLASS.MAGE.value,
      name: 'Arcane Missiles',
      baseDescription:
        'Deal {amount0} damage randomly split among all enemy characters.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ICE_LANCE: {
      type: TYPE.SPELL.value,
      fileName: 'ice_lance',
      class: CLASS.MAGE.value,
      name: 'Ice Lance',
      baseDescription:
        '<b>Freeze</b> a character. If it was already <b>Frozen</b>, deal {amount0} damage instead.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MIRROR_IMAGE: {
      type: TYPE.SPELL.value,
      fileName: 'mirror_image',
      class: CLASS.MAGE.value,
      name: 'Mirror Image',
      baseDescription: 'Summon two 0/2 minions with <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ARCANE_EXPLOSION: {
      type: TYPE.SPELL.value,
      fileName: 'arcane_explosion',
      class: CLASS.MAGE.value,
      name: 'Arcane Explosion',
      baseDescription: 'Deal {amount0} to all enemy minions.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    FROSTBOLT: {
      type: TYPE.SPELL.value,
      fileName: 'frostbolt',
      class: CLASS.MAGE.value,
      name: 'Frostbolt',
      baseDescription:
        'Deal {amount0} damage to a character and <b>Freeze</b> it.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    ARCANE_INTELLECT: {
      type: TYPE.SPELL.value,
      fileName: 'arcane_intellect',
      class: CLASS.MAGE.value,
      name: 'Arcane Intellect',
      baseDescription: 'Draw 2 cards.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    COUNTERSPELL: {
      type: TYPE.SPELL.value,
      fileName: 'counterspell',
      class: CLASS.MAGE.value,
      name: 'Counterspell',
      baseDescription:
        '<b>Secret</b>: When your opponent casts a spell, <b>Counter</b> it.',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    FROST_NOVA: {
      type: TYPE.SPELL.value,
      fileName: 'frost_nova',
      class: CLASS.MAGE.value,
      name: 'Frost Nova',
      baseDescription: '<b>Freeze</b> all enemy minions.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ICE_BARRIER: {
      type: TYPE.SPELL.value,
      fileName: 'ice_barrier',
      class: CLASS.MAGE.value,
      name: 'Ice Barrier',
      baseDescription:
        '<b>Secret</b>: As soon as your hero is attacked, gain 8 armor.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ICE_BLOCK: {
      type: TYPE.SPELL.value,
      fileName: 'ice_block',
      class: CLASS.MAGE.value,
      name: 'Ice Block',
      baseDescription:
        '<b>Secret</b>: When your hero takes fatal damage, prevent it and become <b>Immune</b> this turn.',
      rarity: RARITY.EPIC,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MIRROR_ENTITY: {
      type: TYPE.SPELL.value,
      fileName: 'mirror_entity',
      class: CLASS.MAGE.value,
      name: 'Mirror Entity',
      baseDescription:
        '<b>Secret</b>: When your opponent plays a minion, summon a copy of it.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SPELLBENDER: {
      type: TYPE.SPELL.value,
      fileName: 'spellbender',
      class: CLASS.MAGE.value,
      name: 'Spellbender',
      baseDescription:
        '<b>Secret</b>: When an enemy casts a spell on a minion, summon a 1/3 as the new target.',
      rarity: RARITY.EPIC,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    VAPORIZE: {
      type: TYPE.SPELL.value,
      fileName: 'vaporize',
      class: CLASS.MAGE.value,
      name: 'Vaporize',
      baseDescription:
        '<b>Secret</b>: When a minion attacks your hero, destroy it.',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    CONE_OF_COLD: {
      type: TYPE.SPELL.value,
      fileName: 'cone_of_cold',
      class: CLASS.MAGE.value,
      name: 'Cone of Cold',
      baseDescription:
        '<b>Freeze</b> a minion and the minions next to it, and deal {amount0} damage to them.',
      rarity: RARITY.COMMON,
      cost: 4,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    FIREBALL: {
      type: TYPE.SPELL.value,
      fileName: 'fireball',
      class: CLASS.MAGE.value,
      name: 'Fireball',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [6],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    POLYMORPH: {
      type: TYPE.SPELL.value,
      fileName: 'polymorph',
      class: CLASS.MAGE.value,
      name: 'Polymorph',
      baseDescription: 'Transform a minion into a 1/1 Sheep.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BLIZZARD: {
      type: TYPE.SPELL.value,
      fileName: 'blizzard',
      class: CLASS.MAGE.value,
      name: 'Blizzard',
      baseDescription:
        'Deal {amount0} damage to all enemy minions and <b>Freeze</b> them.',
      rarity: RARITY.RARE,
      cost: 6,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    FLAMESTRIKE: {
      type: TYPE.SPELL.value,
      fileName: 'flamestrike',
      class: CLASS.MAGE.value,
      name: 'Flamestrike',
      baseDescription: 'Deal {amount0} damage to all enemy minions.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    PYROBLAST: {
      type: TYPE.SPELL.value,
      fileName: 'pyroblast',
      class: CLASS.MAGE.value,
      name: 'Pyroblast',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.EPIC,
      cost: 10,
      amount: [10],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    // PALADIN
    BLESSING_OF_MIGHT: {
      type: TYPE.SPELL.value,
      fileName: 'blessing_of_might',
      class: CLASS.PALADIN.value,
      name: 'Blessing of Might',
      baseDescription: 'Give a minion +3 Attack.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BLESSING_OF_WISDOM: {
      type: TYPE.SPELL.value,
      fileName: 'blessing_of_wisdom',
      class: CLASS.PALADIN.value,
      name: 'Blessing of Wisdom',
      baseDescription: 'Choose a minion. Whenever it attacks, draw a card.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    EYE_FOR_AN_EYE: {
      type: TYPE.SPELL.value,
      fileName: 'eye_for_an_eye',
      class: CLASS.PALADIN.value,
      name: 'Eye for an Eye',
      baseDescription:
        '<b>Secret</b>: When your hero takes damage, deal that much damage to the enemy hero.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HAND_OF_PROTECTION: {
      type: TYPE.SPELL.value,
      fileName: 'hand_of_protection',
      class: CLASS.PALADIN.value,
      name: 'Hand of Protection',
      baseDescription: 'Give a minion <b>Divine Shield</b>.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    HUMILITY: {
      type: TYPE.SPELL.value,
      fileName: 'humility',
      class: CLASS.PALADIN.value,
      name: 'Humility',
      baseDescription: "Change a minion's Attack to 1.",
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    NOBLE_SACRIFICE: {
      type: TYPE.SPELL.value,
      fileName: 'noble_sacrifice',
      class: CLASS.PALADIN.value,
      name: 'Noble Sacrifice',
      baseDescription:
        '<b>Secret</b>: When an enemy attacks, summon a 2/1 Defender as the new target.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    REDEMPTION: {
      type: TYPE.SPELL.value,
      fileName: 'redemption',
      class: CLASS.PALADIN.value,
      name: 'Redemption',
      baseDescription:
        '<b>Secret</b>: When a friendly minion dies, return it to life with 1 Health.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    REPENTANCE: {
      type: TYPE.SPELL.value,
      fileName: 'repentance',
      class: CLASS.PALADIN.value,
      name: 'Repentance',
      baseDescription:
        '<b>Secret</b>: After your opponent plays a minion, reduce its Health to 1.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    EQUALITY: {
      type: TYPE.SPELL.value,
      fileName: 'equality',
      class: CLASS.PALADIN.value,
      name: 'Equality',
      baseDescription: 'Change the Health of ALL minions to 1.',
      rarity: RARITY.RARE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HOLY_LIGHT: {
      type: TYPE.SPELL.value,
      fileName: 'holy_light',
      class: CLASS.PALADIN.value,
      name: 'Holy Light',
      baseDescription: 'Restore {amount0} Health.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [6],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    DIVINE_FAVOR: {
      type: TYPE.SPELL.value,
      fileName: 'divine_favor',
      class: CLASS.PALADIN.value,
      name: 'Divine Favor',
      baseDescription:
        'Draw cards until you have as many in hand as your opponent.',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    BLESSING_OF_KINGS: {
      type: TYPE.SPELL.value,
      fileName: 'blessing_of_kings',
      class: CLASS.PALADIN.value,
      name: 'Blessing of Kings',
      baseDescription: 'Give a minion +4/+4. <i>(+4 Attack/+4 Health)</i>.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    CONSECRATION: {
      type: TYPE.SPELL.value,
      fileName: 'consecration',
      class: CLASS.PALADIN.value,
      name: 'Consecration',
      baseDescription: 'Deal {amount0} damage to all enemies.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HAMMER_OF_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'hammer_of_wrath',
      class: CLASS.PALADIN.value,
      name: 'Hammer of Wrath',
      baseDescription: 'Deal {amount0} damage. Draw a card.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BLESSED_CHAMPION: {
      type: TYPE.SPELL.value,
      fileName: 'blessed_champion',
      class: CLASS.PALADIN.value,
      name: 'Blessed Champion',
      baseDescription: "Double a minion's Attack.",
      rarity: RARITY.RARE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    HOLY_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'holy_wrath',
      class: CLASS.PALADIN.value,
      name: 'Holy Wrath',
      baseDescription: 'Draw a card and deal damage equal to its Cost.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    AVENGING_WRATH: {
      type: TYPE.SPELL.value,
      fileName: 'avenging_wrath',
      class: CLASS.PALADIN.value,
      name: 'Avenging Wrath',
      baseDescription:
        'Deal {amount0} damage randomly split among all enemy characters.',
      rarity: RARITY.EPIC,
      cost: 6,
      amount: [8],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    LAY_ON_HANDS: {
      type: TYPE.SPELL.value,
      fileName: 'lay_on_hands',
      class: CLASS.PALADIN.value,
      name: 'Lay on Hands',
      baseDescription: 'Restore {amount0} Health. Draw 3 cards.',
      rarity: RARITY.EPIC,
      cost: 8,
      amount: [8],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    // PRIEST
    CIRCLE_OF_HEALING: {
      type: TYPE.SPELL.value,
      fileName: 'circle_of_healing',
      class: CLASS.PRIEST.value,
      name: 'Circle of Healing',
      baseDescription: 'Restore {amount0} Health to ALL minions.',
      rarity: RARITY.COMMON,
      cost: 0,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SILENCE: {
      type: TYPE.SPELL.value,
      fileName: 'silence',
      class: CLASS.PRIEST.value,
      name: 'Silence',
      baseDescription: '<b>Silence</b> a minion.',
      rarity: RARITY.COMMON,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    HOLY_SMITE: {
      type: TYPE.SPELL.value,
      fileName: 'holy_smite',
      class: CLASS.PRIEST.value,
      name: 'Holy Smite',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    INNER_FIRE: {
      type: TYPE.SPELL.value,
      fileName: 'inner_fire',
      class: CLASS.PRIEST.value,
      name: 'Inner Fire',
      baseDescription: "Change a minion's Attack to be equal to its Health.",
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MIND_VISION: {
      type: TYPE.SPELL.value,
      fileName: 'mind_vision',
      class: CLASS.PRIEST.value,
      name: 'Mind Vision',
      baseDescription:
        "Put a copy of a random card in your opponent's hand into your hand.",
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    POWER_WORD_SHIELD: {
      type: TYPE.SPELL.value,
      fileName: 'power_word_shield',
      class: CLASS.PRIEST.value,
      name: 'Power Word: Shield',
      baseDescription: 'Give a minion +2 Health. Draw a card.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    DIVINE_SPIRIT: {
      type: TYPE.SPELL.value,
      fileName: 'divine_spirit',
      class: CLASS.PRIEST.value,
      name: 'Divine Spirit',
      baseDescription: "Double a minion's Health.",
      rarity: RARITY.COMMON,
      cost: [2],
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MIND_BLAST: {
      type: TYPE.SPELL.value,
      fileName: 'mind_blast',
      class: CLASS.PRIEST.value,
      name: 'Mind Blast',
      baseDescription: 'Deal {amount0} damage to the enemy hero.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SHADOW_WORD_PAIN: {
      type: TYPE.SPELL.value,
      fileName: 'shadow_word_pain',
      class: CLASS.PRIEST.value,
      name: 'Shadow Word: Pain',
      baseDescription: 'Destroy a minion with 3 or less Attack.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SHADOW_WORD_DEATH: {
      type: TYPE.SPELL.value,
      fileName: 'shadow_word_death',
      class: CLASS.PRIEST.value,
      name: 'Shadow Word: Death',
      baseDescription: 'Destroy a minion with 5 or more Attack.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SHADOWFORM: {
      type: TYPE.SPELL.value,
      fileName: 'shadowform',
      class: CLASS.PRIEST.value,
      name: 'Shadowform',
      baseDescription:
        "Your Hero Power becomes 'Deal 2 damage.' If already in Shadowform: 3 damage.",
      rarity: RARITY.EPIC,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    THOUGHTSTEAL: {
      type: TYPE.SPELL.value,
      fileName: 'thoughtsteal',
      class: CLASS.PRIEST.value,
      name: 'Thoughtsteal',
      baseDescription:
        "Copy 2 cards in your opponent's deck and add them to your hand.",
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MASS_DISPEL: {
      type: TYPE.SPELL.value,
      fileName: 'mass_dispel',
      class: CLASS.PRIEST.value,
      name: 'Mass Dispel',
      baseDescription: '<b>Silence</b> all enemy minions. Draw a card.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MINDGAMES: {
      type: TYPE.SPELL.value,
      fileName: 'mindgames',
      class: CLASS.PRIEST.value,
      name: 'Mindgames',
      baseDescription:
        "Put a copy of a random minion from your opponent's deck into the battlefield.",
      rarity: RARITY.EPIC,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SHADOW_MADNESS: {
      type: TYPE.SPELL.value,
      fileName: 'shadow_madness',
      class: CLASS.PRIEST.value,
      name: 'Shadow Madness',
      baseDescription:
        'Gain control of an enemy minion with 3 or less Attack until end of turn.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    HOLY_NOVA: {
      type: TYPE.SPELL.value,
      fileName: 'holy_nova',
      class: CLASS.PRIEST.value,
      name: 'Holy Nova',
      baseDescription:
        'Deal {amount0} damage to all enemies. Restore {amount1} Health to all friendly characters.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [2, 2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HOLY_FIRE: {
      type: TYPE.SPELL.value,
      fileName: 'holy_fire',
      class: CLASS.PRIEST.value,
      name: 'Holy Fire',
      baseDescription:
        'Deal {amount0} damage. Restore {amount1} Health to your hero.',
      rarity: RARITY.RARE,
      cost: 6,
      amount: [5, 5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MIND_CONTROL: {
      type: TYPE.SPELL.value,
      fileName: 'mind_control',
      class: CLASS.PRIEST.value,
      name: 'Mind Control',
      baseDescription: 'Take control of an enemy minion.',
      rarity: RARITY.FREE,
      cost: 10,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    // ROGUE
    BACKSTAB: {
      type: TYPE.SPELL.value,
      fileName: 'backstab',
      class: CLASS.ROGUE.value,
      name: 'Backstab',
      baseDescription: 'Deal {amount0} damage to an undamaged minion.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    PREPARATION: {
      type: TYPE.SPELL.value,
      fileName: 'preparation',
      class: CLASS.ROGUE.value,
      name: 'Preparation',
      baseDescription: 'The nextspell you cast this turn costs (3) less.',
      rarity: RARITY.EPIC,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SHADOWSTEP: {
      type: TYPE.SPELL.value,
      fileName: 'shadowstep',
      class: CLASS.ROGUE.value,
      name: 'Shadowstep',
      baseDescription:
        'Return a friendly minion to your hand. It costs (2) less.',
      rarity: RARITY.COMMON,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    COLD_BLOOD: {
      type: TYPE.SPELL.value,
      fileName: 'cold_blood',
      class: CLASS.ROGUE.value,
      name: 'Cold Blood',
      baseDescription:
        'Give a minion +2 Attack. <b>Combo</b>: +4 Attack instead.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    CONCEAL: {
      type: TYPE.SPELL.value,
      fileName: 'conceal',
      class: CLASS.ROGUE.value,
      name: 'Conceal',
      baseDescription: 'Give your minions <b>Stealth</b> until your next turn.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    DEADLY_POISON: {
      type: TYPE.SPELL.value,
      fileName: 'deadly_poison',
      class: CLASS.ROGUE.value,
      name: 'Deadly Poison',
      baseDescription: 'Give your weapon +2 Attack.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SINISTER_STRIKE: {
      type: TYPE.SPELL.value,
      fileName: 'sinister_strike',
      class: CLASS.ROGUE.value,
      name: 'Sinister Strike',
      baseDescription: 'Deal {amount0} damage to the enemy hero.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    BETRAYAL: {
      type: TYPE.SPELL.value,
      fileName: 'betrayal',
      class: CLASS.ROGUE.value,
      name: 'Betrayal',
      baseDescription:
        'Force an enemy minion to deal its damage to the minions next to it.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BLADE_FLURRY: {
      type: TYPE.SPELL.value,
      fileName: 'blade_flurry',
      class: CLASS.ROGUE.value,
      name: 'Blade Flurry',
      baseDescription:
        'Destroy your weapon and deal its damage to all enemies.',
      rarity: RARITY.RARE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    EVISCERATE: {
      type: TYPE.SPELL.value,
      fileName: 'eviscerate',
      class: CLASS.ROGUE.value,
      name: 'Eviscerate',
      baseDescription:
        'Deal {amount0} damage. <b>Combo</b>: Deal {amount1} damage instead.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [2, 4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SAP: {
      type: TYPE.SPELL.value,
      fileName: 'sap',
      class: CLASS.ROGUE.value,
      name: 'Sap',
      baseDescription: "Return an enemy minion to your opponent's hand.",
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SHIV: {
      type: TYPE.SPELL.value,
      fileName: 'shiv',
      class: CLASS.ROGUE.value,
      name: 'Shiv',
      baseDescription: 'Deal {amount0} damage. Draw a card.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    FAN_OF_KNIVES: {
      type: TYPE.SPELL.value,
      fileName: 'fan_of_knives',
      class: CLASS.ROGUE.value,
      name: 'Fan of Knives',
      baseDescription:
        'Deal {amount0} damage to all enemy minions. Draw a card.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HEADCRACK: {
      type: TYPE.SPELL.value,
      fileName: 'headcrack',
      class: CLASS.ROGUE.value,
      name: 'Headcrack',
      baseDescription:
        'Deal {amount0} damage to the enemy hero. <b>Combo</b>: Return this to your hand next turn.',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    ASSASSINATE: {
      type: TYPE.SPELL.value,
      fileName: 'assassinate',
      class: CLASS.ROGUE.value,
      name: 'Assassinate',
      baseDescription: 'Destroy an enemy minion.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    VANISH: {
      type: TYPE.SPELL.value,
      fileName: 'vanish',
      class: CLASS.ROGUE.value,
      name: 'Vanish',
      baseDescription: "Return all minions to their owner's hand.",
      rarity: RARITY.COMMON,
      cost: 6,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SPRINT: {
      type: TYPE.SPELL.value,
      fileName: 'sprint',
      class: CLASS.ROGUE.value,
      name: 'Sprint',
      baseDescription: 'Draw 4 cards.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    // SHAMAN
    ANCESTRAL_HEALING: {
      type: TYPE.SPELL.value,
      fileName: 'ancestral_healing',
      class: CLASS.SHAMAN.value,
      name: 'Ancestral Healing',
      baseDescription:
        'Restore a minion to full Health and give it <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    TOTEMIC_MIGHT: {
      type: TYPE.SPELL.value,
      fileName: 'totemic_might',
      class: CLASS.SHAMAN.value,
      name: 'Totemic Might',
      baseDescription: 'Give your Totems +2 Health.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    EARTH_SHOCK: {
      type: TYPE.SPELL.value,
      fileName: 'earth_shock',
      class: CLASS.SHAMAN.value,
      name: 'Earth Shock',
      baseDescription:
        '<b>Silence</b> a minion, then deal {amount0} damage to it.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    FORKED_LIGHTNING: {
      type: TYPE.SPELL.value,
      fileName: 'forked_lightning',
      class: CLASS.SHAMAN.value,
      name: 'Forked Lightning',
      baseDescription:
        'Deal {amount0} damage to 2 random enemy minions. <b>Overload</b>: ({overload})',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [2],
      affectedBySpellpower: true,
      overload: 2,
      requiresTarget: false,
      obtainable: true,
    },
    FROST_SHOCK: {
      type: TYPE.SPELL.value,
      fileName: 'frost_shock',
      class: CLASS.SHAMAN.value,
      name: 'Frost Shock',
      baseDescription:
        'Deal {amount0} damage to an enemy character and <b>Freeze</b> it.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    LIGHTNING_BOLT: {
      type: TYPE.SPELL.value,
      fileName: 'lightning_bolt',
      class: CLASS.SHAMAN.value,
      name: 'Lightning Bolt',
      baseDescription: 'Deal {amount0} damage. <b>Overload</b>: ({overload})',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [3],
      affectedBySpellpower: true,
      overload: 1,
      requiresTarget: true,
      obtainable: true,
    },
    ROCKBITER_WEAPON: {
      type: TYPE.SPELL.value,
      fileName: 'rockbiter_weapon',
      class: CLASS.SHAMAN.value,
      name: 'Rockbiter Weapon',
      baseDescription: 'Give a friendly character +3 Attack this turn.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    ANCESTRAL_SPIRIT: {
      type: TYPE.SPELL.value,
      fileName: 'ancestral_spirit',
      class: CLASS.SHAMAN.value,
      name: 'Ancestral Spirit',
      baseDescription:
        'Choose a minion. When that minion is destroyed, return it to the battlefield.',
      rarity: RARITY.RARE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    WINDFURY: {
      type: TYPE.SPELL.value,
      fileName: 'windfury',
      class: CLASS.SHAMAN.value,
      name: 'Windfury',
      baseDescription: 'Give a minion <b>Windfury</b>.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    FAR_SIGHT: {
      type: TYPE.SPELL.value,
      fileName: 'far_sight',
      class: CLASS.SHAMAN.value,
      name: 'Far Sight',
      baseDescription: 'Draw a card. That card costs (3) less.',
      rarity: RARITY.EPIC,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    FERAL_SPIRIT: {
      type: TYPE.SPELL.value,
      fileName: 'feral_spirit',
      class: CLASS.SHAMAN.value,
      name: 'Feral Spirit',
      baseDescription:
        'Summon two 2/3 Spirit Wolves with <b>Taunt</b>. <b>Overload</b>: ({overload})',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 2,
      requiresTarget: false,
      obtainable: true,
    },
    HEX: {
      type: TYPE.SPELL.value,
      fileName: 'hex',
      class: CLASS.SHAMAN.value,
      name: 'Hex',
      baseDescription: 'Transform a minion into a 0/1 Frog with <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    LAVA_BURST: {
      type: TYPE.SPELL.value,
      fileName: 'lava_burst',
      class: CLASS.SHAMAN.value,
      name: 'Lava Burst',
      baseDescription: 'Deal {amount0} damage. <b>Overload</b>: ({overload})',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [5],
      affectedBySpellpower: true,
      overload: 2,
      requiresTarget: true,
      obtainable: true,
    },
    LIGHTNING_STORM: {
      type: TYPE.SPELL.value,
      fileName: 'lightning_storm',
      class: CLASS.SHAMAN.value,
      name: 'Lightning Storm',
      baseDescription:
        'Deal {amount0}-{amount1} damage to all enemy minions. <b>Overload</b>: ({overload})',
      rarity: RARITY.RARE,
      cost: 3,
      amount: [2, 3],
      affectedBySpellpower: true,
      overload: 2,
      requiresTarget: false,
      obtainable: true,
    },
    BLOODLUST: {
      type: TYPE.SPELL.value,
      fileName: 'bloodlust',
      class: CLASS.SHAMAN.value,
      name: 'Bloodlust',
      baseDescription: 'Give your minions +3 Attack this turn.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    // WARLOCK
    SACRIFICIAL_PACT: {
      type: TYPE.SPELL.value,
      fileName: 'sacrificial_pact',
      class: CLASS.WARLOCK.value,
      name: 'Sacrificial Pact',
      baseDescription:
        'Destroy a Demon. Restore {amount0} Health to your hero.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [5],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SOULFIRE: {
      type: TYPE.SPELL.value,
      fileName: 'soulfire',
      class: CLASS.WARLOCK.value,
      name: 'Soulfire',
      baseDescription: 'Deal {amount0} damage. Discard a random card.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    CORRUPTION: {
      type: TYPE.SPELL.value,
      fileName: 'corruption',
      class: CLASS.WARLOCK.value,
      name: 'Corruption',
      baseDescription:
        'Choose an enemy minion. At the start of your turn, destroy it.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    MORTAL_COIL: {
      type: TYPE.SPELL.value,
      fileName: 'mortal_coil',
      class: CLASS.WARLOCK.value,
      name: 'Mortal Coil',
      baseDescription:
        'Deal {amount0} damage to a minion. If that kills it, draw a card.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    POWER_OVERWHELMING: {
      type: TYPE.SPELL.value,
      fileName: 'power_overwhelming',
      class: CLASS.WARLOCK.value,
      name: 'Power Overwhelming',
      baseDescription:
        'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    DEMONFIRE: {
      type: TYPE.SPELL.value,
      fileName: 'demonfire',
      class: CLASS.WARLOCK.value,
      name: 'Demonfire',
      baseDescription:
        "Deal {amount0} damage to a minion. If it's a friendly Demon, give it +2/+2 instead.",
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    DRAIN_LIFE: {
      type: TYPE.SPELL.value,
      fileName: 'drain_life',
      class: CLASS.WARLOCK.value,
      name: 'Drain Life',
      baseDescription:
        'Deal {amount0} damage. Restore {amount1} Health to your hero.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [2, 2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SENSE_DEMONS: {
      type: TYPE.SPELL.value,
      fileName: 'sense_demons',
      class: CLASS.WARLOCK.value,
      name: 'Sense Demons',
      baseDescription: 'Draw 2 Demons from your deck.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SHADOW_BOLT: {
      type: TYPE.SPELL.value,
      fileName: 'shadow_bolt',
      class: CLASS.WARLOCK.value,
      name: 'Shadow Bolt',
      baseDescription: 'Deal {amount0} damage to a minion.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [4],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    HELLFIRE: {
      type: TYPE.SPELL.value,
      fileName: 'hellfire',
      class: CLASS.WARLOCK.value,
      name: 'Hellfire',
      baseDescription: 'Deal {amount0} damage to ALL characters.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    SHADOWFLAME: {
      type: TYPE.SPELL.value,
      fileName: 'shadowflame',
      class: CLASS.WARLOCK.value,
      name: 'Shadowflame',
      baseDescription:
        'Destroy a friendly minion and deal its Attack damage to all enemy minions.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BANE_OF_DOOM: {
      type: TYPE.SPELL.value,
      fileName: 'bane_of_doom',
      class: CLASS.WARLOCK.value,
      name: 'Bane of Doom',
      baseDescription:
        'Deal {amount0} damage to a character. If that kills it, summon a random Demon.',
      rarity: RARITY.EPIC,
      cost: 5,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SIPHON_SOUL: {
      type: TYPE.SPELL.value,
      fileName: 'siphon_soul',
      class: CLASS.WARLOCK.value,
      name: 'Siphon Soul',
      baseDescription:
        'Destroy a minion. Restore {amount0} Health to your hero.',
      rarity: RARITY.RARE,
      cost: 6,
      amount: [3],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    TWISTING_NETHER: {
      type: TYPE.SPELL.value,
      fileName: 'twisting_nether',
      class: CLASS.WARLOCK.value,
      name: 'Twisting Nether',
      baseDescription: 'Destroy all minions.',
      rarity: RARITY.EPIC,
      cost: 8,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    // WARRIOR
    INNER_RAGE: {
      type: TYPE.SPELL.value,
      fileName: 'inner_rage',
      class: CLASS.WARRIOR.value,
      name: 'Inner Rage',
      baseDescription:
        'Deal {amount0} damage to a minion and give it +2 Attack.',
      rarity: RARITY.COMMON,
      cost: 0,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    EXECUTE: {
      type: TYPE.SPELL.value,
      fileName: 'execute',
      class: CLASS.WARRIOR.value,
      name: 'Execute',
      baseDescription: 'Destroy a damaged enemy minion.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SHIELD_SLAM: {
      type: TYPE.SPELL.value,
      fileName: 'shield_slam',
      class: CLASS.WARRIOR.value,
      name: 'Shield Slam',
      baseDescription: 'Deal 1 damage to a minion for each Armor you have.',
      rarity: RARITY.EPIC,
      cost: 1,
      amount: [0],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    UPGRADE: {
      type: TYPE.SPELL.value,
      fileName: 'upgrade',
      class: CLASS.WARRIOR.value,
      name: 'Upgrade!',
      baseDescription:
        'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon.',
      rarity: RARITY.RARE,
      cost: 1,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    WHIRLWIND: {
      type: TYPE.SPELL.value,
      fileName: 'whirlwind',
      class: CLASS.WARRIOR.value,
      name: 'Whirlwind',
      baseDescription: 'Deal {amount0} damage to ALL minions.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: [1],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    BATTLE_RAGE: {
      type: TYPE.SPELL.value,
      fileName: 'battle_rage',
      class: CLASS.WARRIOR.value,
      name: 'Battle Rage',
      baseDescription: 'Draw a card for each damaged friendly character.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    CLEAVE: {
      type: TYPE.SPELL.value,
      fileName: 'cleave',
      class: CLASS.WARRIOR.value,
      name: 'Cleave',
      baseDescription: 'Deal {amount0} damage to two random enemy minions.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    COMMANDING_SHOUT: {
      type: TYPE.SPELL.value,
      fileName: 'commanding_shout',
      class: CLASS.WARRIOR.value,
      name: 'Commanding Shout',
      baseDescription:
        "Your minions can't be reduced below 1 Health this turn. Draw a card.",
      rarity: RARITY.RARE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    HEROIC_STRIKE: {
      type: TYPE.SPELL.value,
      fileName: 'heroic_strike',
      class: CLASS.WARRIOR.value,
      name: 'Heroic Strike',
      baseDescription: 'Give your hero +4 Attack this turn.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    RAMPAGE: {
      type: TYPE.SPELL.value,
      fileName: 'rampage',
      class: CLASS.WARRIOR.value,
      name: 'Rampage',
      baseDescription: 'Give a damaged minion +3/+3.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SLAM: {
      type: TYPE.SPELL.value,
      fileName: 'slam',
      class: CLASS.WARRIOR.value,
      name: 'Slam',
      baseDescription:
        'Deal {amount0} damage to a minion. If it survives, draw a card.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: [2],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    CHARGE: {
      type: TYPE.SPELL.value,
      fileName: 'charge',
      class: CLASS.WARRIOR.value,
      name: 'Charge',
      baseDescription: 'Give a friendly minion +2 Attack and <b>Charge</b>.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [2],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    SHIELD_BLOCK: {
      type: TYPE.SPELL.value,
      fileName: 'shield_block',
      class: CLASS.WARRIOR.value,
      name: 'Shield Block',
      baseDescription: 'Gain 5 Armor. Draw a card.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },
    MORTAL_STRIKE: {
      type: TYPE.SPELL.value,
      fileName: 'mortal_strike',
      class: CLASS.WARRIOR.value,
      name: 'Mortal Strike',
      baseDescription:
        'Deal {amount0} damage. If you have 12 or less Health, deal {amount1} instead.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: [4, 6],
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
      obtainable: true,
    },
    BRAWL: {
      type: TYPE.SPELL.value,
      fileName: 'brawl',
      class: CLASS.WARRIOR.value,
      name: 'Brawl',
      baseDescription:
        'Destroy all minions except one. <i>(chosen randomly)</i>',
      rarity: RARITY.EPIC,
      cost: 5,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: true,
    },

    // OTHER

    // DRUID
    KEEPER_OF_THE_GROVE_CHOOSE_ONE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: '',
      class: CLASS.DRUID.value,
      name: 'Choose One',
      baseDescription: '',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    KEEPER_OF_THE_GROVE_CHOOSE_ONE_DISPEL: {
      type: TYPE.GENERIC.value,
      fileName: 'keeper_of_the_grove_choose_one_dispel',
      class: CLASS.DRUID.value,
      name: 'Dispel',
      baseDescription: '<b>Silence</b> a minion.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    KEEPER_OF_THE_GROVE_CHOOSE_ONE_MOONFIRE: {
      type: TYPE.GENERIC.value,
      fileName: 'keeper_of_the_grove_choose_one_moonfire',
      class: CLASS.DRUID.value,
      name: 'Moonfire',
      baseDescription: 'Deal {amount0} damage.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: [2],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    DRUID_OF_THE_CLAW_CHOOSE_ONE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: 'druid_of_the_claw_choose_one',
      class: CLASS.DRUID.value,
      name: 'Choose One',
      baseDescription: '',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    ANCIENT_OF_LORE_CHOOSE_ONE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: '',
      class: CLASS.DRUID.value,
      name: 'Choose One',
      baseDescription: '',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    ANCIENT_OF_LORE_CHOOSE_ONE_ANCIENT_SECRETS: {
      type: TYPE.GENERIC.value,
      fileName: 'ancient_of_lore_choose_one_ancient_secrets',
      class: CLASS.DRUID.value,
      name: 'Ancient Secrets',
      baseDescription: 'Restore {amount0} Health.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [7],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
      obtainable: false,
    },
    ANCIENT_OF_LORE_CHOOSE_ONE_ANCIENT_TEACHINGS: {
      type: TYPE.GENERIC.value,
      fileName: 'ancient_of_lore_choose_one_ancient_teachings',
      class: CLASS.DRUID.value,
      name: 'Ancient Teachings',
      baseDescription: 'Draw 2 cards.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    ANCIENT_OF_WAR_CHOOSE_ONE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: '',
      class: CLASS.DRUID.value,
      name: 'Choose One',
      baseDescription: '',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    ANCIENT_OF_WAR_CHOOSE_ONE_ROOTED: {
      type: TYPE.GENERIC.value,
      fileName: 'ancient_of_war_choose_one_rooted',
      class: CLASS.DRUID.value,
      name: 'Rooted',
      baseDescription: '+5 Health and <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    ANCIENT_OF_WAR_CHOOSE_ONE_UPROOT: {
      type: TYPE.GENERIC.value,
      fileName: 'ancient_of_war_choose_one_uproot',
      class: CLASS.DRUID.value,
      name: 'Uproot',
      baseDescription: '+5 Attack.',
      rarity: RARITY.FREE,
      cost: 7,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    CENARIUS_ONE: {
      type: TYPE.CHOOSE_ONE.value,
      fileName: '',
      class: CLASS.DRUID.value,
      name: 'Choose One',
      baseDescription: '',
      rarity: RARITY.FREE,
      cost: 0,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    CENARIUS_ONE_DEMIGODS_FAVOR: {
      type: TYPE.GENERIC.value,
      fileName: 'cenarius_choose_one_demigods_favor',
      class: CLASS.DRUID.value,
      name: "Demigod's Favor",
      baseDescription: 'Give your other minions +2/+2.',
      rarity: RARITY.FREE,
      cost: 8,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
    CENARIUS_CHOOSE_ONE_SHANDOS_LESSON: {
      type: TYPE.GENERIC.value,
      fileName: 'cenarius_choose_one_shandos_lesson',
      class: CLASS.DRUID.value,
      name: "Shan'do's Lesson",
      baseDescription: 'Summon two 2/2 Treants with <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 8,
      amount: [0],
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
      obtainable: false,
    },
  }

module.exports = {
  EFFECT_IDS,
  EFFECT_DATA,
}
