const RARITY = {
    COMMON: 'Common',
    FREE: 'Free',
    RARE: 'Rare',
    EPIC: 'Epic',
    LEGENDARY: 'Legendary',
  },
  EFFECT_IDS = {
    INNERVATE: [0, 'innervate'], // DRUID
    MOONFIRE: [1, 'moonfire'],
    CLAW: [2, 'claw'],
    NATURALIZE: [3, 'naturalize'],
    SAVAGERY: [4, 'savagery'],
    MARK_OF_THE_WILD: [5, 'mark_of_the_wild'],
    POWER_OF_THE_WILD: [6, 'power_of_the_wild'],
    WILD_GROWTH: [7, 'wild_growth'],
    WRATH: [8, 'wrath'],
    HEALING_TOUCH: [9, 'healing_touch'],
    MARK_OF_NATURE: [10, 'mark_of_nature'],
    SAVAGE_ROAR: [11, 'savage_roar'],
    BITE: [12, 'bite'],
    SOUL_OF_THE_FOREST: [13, 'soul_of_the_forest'],
    SWIPE: [14, 'swipe'],
    NOURISH: [15, 'nourish'],
    STARFALL: [16, 'starfall'],
    FORCE_OF_NATURE: [17, 'force_of_nature'],
    STARFIRE: [18, 'starfire'],

    HUNTERS_MARK: [19, 'hunters_mark'], // HUNTER
    ARCANE_SHOT: [20, 'arcane_shot'],
    BESTIAL_WRATH: [21, 'bestial_wrath'],
    FLARE: [22, 'flare'],
    TRACKING: [23, 'tracking'],
    EXPLOSIVE_TRAP: [24, 'explosive_trap'],
    FREEZING_TRAP: [25, 'freezing_trap'],
    MISDIRECTION: [26, 'misdirection'],
    SNAKE_TRAP: [27, 'snake_trap'],
    SNIPE: [28, 'snipe'],
    ANIMAL_COMPANION: [29, 'animal_companion'],
    DEADLY_SHOT: [30, 'deadly_shot'],
    KILL_COMMAND: [31, 'kill_command'],
    UNLEASH_THE_HOUNDS: [32, 'unleash_the_hounds'],
    MULTI_SHOT: [33, 'multi_shot'],
    EXPLOSIVE_SHOT: [34, 'explosive_shot'],

    ARCANE_MISSILES: [35, 'arcane_missiles'], // MAGE
    ICE_LANE: [36, 'ice_lane'],
    MIRROR_IMAGE: [37, 'mirror_image'],
    ARCANE_EXPLOSION: [38, 'arcane_explosion'],
    FROSTBOLT: [39, 'frostbolt'],
    ARCANE_INTELLECT: [40, 'arcane_intellect'],
    COUNTERSPELL: [41, 'counterspell'],
    FROST_NOVA: [42, 'frost_nova'],
    ICE_BARRIER: [43, 'ice_barrier'],
    ICE_BLOCK: [44, 'ice_block'],
    MIRROR_ENTITY: [45, 'mirror_entity'],
    SPELLBENDER: [46, 'spellbender'],
    VAPORIZE: [47, 'vaporize'],
    CONE_OF_COLD: [48, 'cone_of_cold'],
    FIREBALL: [49, 'fireball'],
    POLYMORPH: [50, 'polymorph'],
    BLIZZARD: [51, 'blizzard'],
    FLAMESTRIKE: [52, 'flamestrike'],
    PYROBLAST: [53, 'pyroblast'],

    BLESSING_OF_MIGHT: [54, 'blessing_of_might'], // PALADIN
    BLESSING_OF_WISDOM: [55, 'blessing_of_wisdom'],
    EYE_FOR_AN_EYE: [56, 'eye_for_an_eye'],
    HAND_OF_PROTECTION: [57, 'hand_of_protection'],
    HUMILITY: [58, 'humility'],
    NOBLE_SACRIFICE: [59, 'noble_sacrifice'],
    REDEMPTION: [60, 'redemption'],
    REPENTANCE: [61, 'repentance'],
    EQUALITY: [62, 'equality'],
    HOLY_LIGHT: [63, 'holy_light'],
    DIVINE_FAVOR: [64, 'divine_favor'],
    BLESSING_OF_KINGS: [65, 'blessing_of_kings'],
    CONSECRATION: [66, 'consecration'],
    HAMMER_OF_WRATH: [67, 'hammer_of_wrath'],
    BLESSED_CHAMPION: [68, 'blessed_champion'],
    HOLY_WRATH: [69, 'holy_wrath'],
    AVENGING_WRATH: [70, 'avenging_wrath'],
    LAY_ON_HANDS: [71, 'lay_on_hands'],

    CIRCLE_OF_HEALING: [72, 'circle_of_healing'], // PRIEST
    SILENCE: [73, 'silence'],
    HOLY_SMITE: [74, 'holy_smite'],
    INNER_FIRE: [75, 'inner_fire'],
    MIND_VISION: [76, 'mind_vision'],
    POWER_WORD_SHIELD: [77, 'power_word_shield'],
    DIVINE_SPIRIT: [78, 'divine_spirit'],
    MIND_BLAST: [79, 'mind_blast'],
    SHADOW_WORD_PAIN: [80, 'shadow_word_pain'],
    SHADOW_WORD_DEATH: [81, 'shadow_word_death'],
    SHADOWFORM: [82, 'shadowform'],
    THOUGHTSTEAL: [83, 'thoughtsteal'],
    MASS_DISPEL: [84, 'mass_dispel'],
    MINDGAMES: [85, 'mindgames'],
    SHADOW_MADNESS: [86, 'shadow_madness'],
    HOLY_NOVA: [87, 'holy_nova'],
    HOLY_FIRE: [88, 'holy_fire'],
    MIND_CONTROL: [89, 'mind_control'],

    BACKSTAB: [90, 'backstab'], // ROGUE
    PREPARATION: [91, 'preparation'],
    SHADOWSTEP: [92, 'shadowstep'],
    COLD_BLOOD: [93, 'cold_blood'],
    CONCEAL: [94, 'conceal'],
    DEADLY_POISON: [95, 'deadly_poison'],
    SINISTER_STRIKE: [96, 'sinister_strike'],
    BETRAYAL: [97, 'betrayal'],
    BLADE_FLURRY: [98, 'blade_flurry'],
    EVISCERATE: [99, 'eviscerate'],
    SAP: [100, 'sap'],
    SHIV: [101, 'shiv'],
    FAN_OF_KNIVES: [102, 'fan_of_knives'],
    HEADCRACK: [103, 'headcrack'],
    ASSASSINATE: [104, 'assassinate'],
    VANISH: [105, 'vanish'],
    SPRINT: [106, 'sprint'],

    ANCESTRAL_HEALING: [107, 'ancestral_healing'], // SHAMAN
    TOTEMIC_MIGHT: [108, 'totemic_might'],
    EARTH_SHOCK: [109, 'earth_shock'],
    FORKED_LIGHTNING: [110, 'forked_lightning'],
    FROST_SHOCK: [111, 'frost_shock'],
    LIGHTNING_BOLT: [112, 'lightning_bolt'],
    ROCKBITER_WEAPONG: [113, 'rockbiter_weapon'],
    ANCESTRAL_SPIRIT: [114, 'ancestral_spirit'],
    WINDFURY: [115, 'windfury'],
    FAR_SIGHT: [116, 'far_sight'],
    FERAL_SPIRIT: [117, 'feral_spirit'],
    HEX: [118, 'hex'],
    LAVA_BURST: [119, 'lava_burst'],
    LIGHTNING_STORM: [120, 'lightning_storm'],
    BLOODLUST: [121, 'bloodlust'],

    SACRIFICIAL_PACT: [122, 'sacrificial_pact'], // WARLOCK
    SOULFIRE: [123, 'soulfire'],
    CORRUPTION: [124, 'corruption'],
    MORTAL_COIL: [125, 'mortal_coil'],
    POWER_OVERWHELMING: [126, 'power_overwhelming'],
    DEMONFIRE: [127, 'demonfire'],
    DRAIN_LIFE: [128, 'drain_life'],
    SENSE_DEMONS: [129, 'sense_demons'],
    SHADOW_BOLT: [130, 'shadow_bolt'],
    HELLFIRE: [131, 'hellfire'],
    SHADOWFLAME: [132, 'shadowflame'],
    BANE_OF_DOOM: [133, 'bane_of_doom'],
    SIPHON_SOUL: [134, 'siphon_soul'],
    TWISTING_NETHER: [135, 'twisting_nether'],

    INNER_RAGE: [136, 'inner_rage'], // WARRIOR
    EXECUTE: [137, 'execute'],
    SHIELD_SLAM: [138, 'shield_slam'],
    UPGRADE: [139, 'upgrade'],
    WHIRLWIND: [140, 'whirlwind'],
    BATTLE_RAGE: [141, 'battle_rage'],
    CLEAVE: [142, 'cleave'],
    COMMANDING_SHOUT: [143, 'commanding_shout'],
    HEROIC_STRIKE: [144, 'heroic_strike'],
    RAMPAGE: [145, 'rampage'],
    SLAM: [146, 'slam'],
    CHARGE: [147, 'charge'],
    SHIELD_BLOCK: [148, 'shield_block'],
    MORTAL_STRIKE: [149, 'mortal_strike'],
    BRAWL: [150, 'brawl'],
  },
  EFFECT_DATA = [
    // effect objects will have more data than this
    // these are just the baseline values

    // DRUID
    {
      name: 'Innervate',
      baseDescription: 'Gain 2 Mana Crystals this turn only.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: 0, // doesn't apply when not affected by spellpower
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Moonfire',
      baseDescription: 'Deal {amount} damage.',
      rarity: RARITY.FREE,
      cost: 0,
      amount: 1,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Claw',
      baseDescription: 'Give your hero +2 Attack this turn. Gain 2 Armor.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Naturalize',
      baseDescription: 'Destroy a minion. Your opponent draws 2cards.',
      rarity: RARITY.COMMON,
      cost: 1,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Savagery',
      baseDescription: "Deal damage equal to your hero's Attack to a minion.",
      rarity: RARITY.RARE,
      cost: 1,
      amount: 0,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Mark of the Wild',
      baseDescription:
        'Give a minion <b>Taunt</b> and +2/+2. <i>(+2 Attack/+2 Health)</i>',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Power of the Wild',
      baseDescription:
        '<b>Choose One</b> - Give your minions +1/+1; or Summon a 3/2 Panther.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Leader of the Pack',
      baseDescription: 'Give your minions +1/+1.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Summon a Panther',
      baseDescription: 'Summon a 3/2 Panther.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Wild Growth',
      baseDescription: 'Gain an empty Mana Crystal.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Wrath',
      baseDescription:
        '<b>Choose One</b> - Deal {amount1} damage to a minion; or {amount2} damage and draw a card.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: 3,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: "Nature's Wrath",
      baseDescription: 'Deal {amount} damage to a minion. Draw a card.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 1,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Solar Wrath',
      baseDescription: 'Deal {amount} damage to a minion.',
      rarity: RARITY.FREE,
      cost: 2,
      amount: 3,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Healing Touch',
      baseDescription: 'Restore {amount} Health.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 8,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: ytue,
    },
    {
      name: 'Mark of Nature',
      baseDescription:
        '<b>Choose One</b> - Give a minion +4 Attack; or +4 Health and <b>Taunt</b>.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: "Tiger's Fury",
      baseDescription: 'Give a minion +4 Attack.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Thick Hide',
      baseDescription: 'Give a minion +4 Health and <b>Taunt</b>.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Savage Roar',
      baseDescription: 'Give your characters +2 Attack this turn.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Bite',
      baseDescription: 'Give your hero +4 Attack this turn. Gain 4 Armor.',
      rarity: RARITY.RARE,
      cost: 4,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Soul of the Forest',
      baseDescription:
        'Give your minions "<b>Deathrattle<\b>: Summon a 2/2 Treant."',
      rarity: RARITY.COMMON,
      cost: 4,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Swipe',
      baseDescription:
        'Deal {amount1} damage to an enemy and {amount2} damage  to all other enemies.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: 4,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Nourish',
      baseDescription:
        '<b>Choose One</b> - Gain 2 Mana Crystal; or Draw 3 cards.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Enrich',
      baseDescription: 'Draw 3 cards.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Rampant Growth',
      baseDescription: 'Gain 2 Mana Crystals.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Starfall',
      baseDescription:
        '<b>Choose One</b> - Deal {amount1} damage to a minion; or {amount2} damage to all enemy minions.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: 5,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Starlord',
      baseDescription: 'Deal {amount} damage to a minion.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: 5,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Stellar Drift',
      baseDescription: 'Deal {amount} damage to all enemy minions.',
      rarity: RARITY.FREE,
      cost: 5,
      amount: 2,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Force of Nature',
      baseDescription:
        'Summon three 2/2 Treants with <b>Charge</b> that die at the end of the turn.',
      rarity: RARITY.EPIC,
      cost: 6,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Starfire',
      baseDescription: 'Deal {amount} damage. Draw a card.',
      rarity: RARITY.FREE,
      cost: 6,
      amount: 5,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    // HUNTER
    {
      name: "Hunter's Mark",
      baseDescription: "Change a minion's Health to 1.",
      rarity: RARITY.FREE,
      cost: 0,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Arcane Shot',
      baseDescription: 'Deal {amount} damage.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: 2,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Bestial Wrath',
      baseDescription: 'Give a Beast +2 Attack and <b>Immune</b> this turn.',
      rarity: RARITY.EPIC,
      cost: 1,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Flare',
      baseDescription:
        'All minions lose <b>Stealth</b>.\nDestroy all enemy\n<b>Secrets</b>. Draw a card.',
      rarity: RARITY.RARE,
      cost: 1,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Tracking',
      baseDescription:
        'Look at the top 3 cards of your deck. Draw one and discard the others.',
      rarity: RARITY.FREE,
      cost: 1,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Explosive Trap',
      baseDescription:
        '<b>Secret</b>: When your hero is attacked, deal {amount} damage to all enemies.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: 2,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Freezing Trap',
      baseDescription:
        "<b>Secret</b>: When an enemy minion attacks, return it to its owner's hand. It costs (2) more.",
      rarity: RARITY.COMMON,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Misdirection',
      baseDescription:
        '<b>Secret</b>: When an enemy attacks your hero, instead it attacks another random character.',
      rarity: RARITY.RARE,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Snake Trap',
      baseDescription:
        '<b>Secret</b>: When one of your minions is attacked, summon three 1/1 Snakes.',
      rarity: RARITY.EPIC,
      cost: 2,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Snipe',
      baseDescription:
        '<b>Secret</b>: After your opponent plays a minion, deal {amount} damage to it.',
      rarity: RARITY.COMMON,
      cost: 2,
      amount: 4,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Animal Companion',
      baseDescription: 'Summon a random Beast Companion.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Deadly Shot',
      baseDescription: 'Destroy a random enemy minion.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Kill Command',
      baseDescription:
        'Deal {amount1} damage. If you control a Beast, deal {amount2} damage instead.',
      rarity: RARITY.FREE,
      cost: 3,
      amount: 5,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    {
      name: 'Unleash the Hounds',
      baseDescription:
        'For each enemy minion, summon a 1/1 Hound with <b>Charge</b>.',
      rarity: RARITY.COMMON,
      cost: 3,
      amount: 0,
      affectedBySpellpower: false,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Multi-Shot',
      baseDescription: 'Deal {amount} damage to two random enemy  minions.',
      rarity: RARITY.FREE,
      cost: 4,
      amount: 3,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: false,
    },
    {
      name: 'Explosive Shot',
      baseDescription:
        'Deal {amount1} damage to a minion and {amount2} damage to adjacent ones.',
      rarity: RARITY.RARE,
      cost: 5,
      amount: 5,
      affectedBySpellpower: true,
      overload: 0,
      requiresTarget: true,
    },
    // MAGE
    {
      name: 'Mana Wyrm',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: "Sorcerer's Apprentice",
      description: '',
      stats: [2, 3, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Kirin Tor Mage',
      description: '',
      stats: [3, 4, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Ethereal Arcanist',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Water Elemental',
      description: '',
      stats: [4, 3, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Archmage Antonidas',
      description: '',
      stats: [7, 5, 7],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      // PALADIN
      name: 'Argent Protector',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Aldor Peacekeeper',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Guardian of Kings',
      description: '',
      stats: [7, 5, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Tirion Fordring',
      description: '',
      stats: [8, 6, 6],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      // PRIEST
      name: 'Northshire Cleric',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Lightwell',
      description: '',
      stats: [2, 0, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Auchenai Soulpriest',
      description: '',
      stats: [4, 3, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Lightspawn',
      description: '',
      stats: [4, 0, 5],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Cabal Shadow Priest',
      description: '',
      stats: [6, 4, 5],
      rarity: RARITY.EPIC,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Temple Enforcer',
      description: '',
      stats: [6, 6, 6],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Prophet Velen',
      description: '',
      stats: [7, 7, 7],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      // ROGUE
      name: 'Defias Ring Leader',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Patient Assassin',
      description: '',
      stats: [2, 1, 1],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, true, false, false, true],
    },
    {
      name: 'Edwin VanCleef',
      description: '',
      stats: [3, 2, 2],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'SI:7 Agent',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Master of Disguise',
      description: '',
      stats: [4, 4, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Kidnapper',
      description: '',
      stats: [6, 5, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.UNDEAD,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      // SHAMAN
      name: 'Dust Devil',
      description: '',
      stats: [1, 3, 1],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 2,
      attributes: [false, false, false, false, true, false, false],
    },
    {
      name: 'Flametongue Totem',
      description: '',
      stats: [2, 0, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.TOTEM,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Mana Tide Totem',
      description: '',
      stats: [3, 0, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.TOTEM,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Unbound Elemental',
      description: '',
      stats: [3, 2, 4],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Windspeaker',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Earth Elemental',
      description: '',
      stats: [5, 7, 8],
      rarity: RARITY.EPIC,
      tribe: TRIBE.NONE,
      overload: 3,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      name: 'Fire Elemental',
      description: '',
      stats: [6, 6, 5],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: "Al'Akir the Windlord",
      description: '',
      stats: [8, 3, 5],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, true, true, false, true, false, false],
    },
    {
      // WARLOCK
      name: 'Blood Imp',
      description: '',
      stats: [1, 0, 1],
      rarity: RARITY.COMMON,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, true, false, false, false],
    },
    {
      name: 'Flame Imp',
      description: '',
      stats: [1, 3, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Voidwalker',
      description: '',
      stats: [1, 1, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      name: 'Felstalker',
      description: '',
      stats: [2, 4, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Felguard',
      description: '',
      stats: [3, 3, 5],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, true, false, false, false, false, false],
    },
    {
      name: 'Void Terror',
      description: '',
      stats: [3, 3, 3],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Pit Lord',
      description: '',
      stats: [4, 5, 6],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Summoning Portal',
      description: '',
      stats: [4, 0, 4],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Doomguard',
      description: '',
      stats: [5, 5, 7],
      rarity: RARITY.RARE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
    {
      name: 'Dread Infernal',
      description: '',
      stats: [6, 6, 6],
      rarity: RARITY.FREE,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Lord Jaraxxus',
      description: '',
      stats: [9, 3, 15],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.DEMON,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      // WARRIOR
      name: 'Armorsmith',
      description: '',
      stats: [2, 1, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Cruel Taskmaster',
      description: '',
      stats: [2, 2, 2],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Frothing Berserker',
      description: '',
      stats: [3, 2, 4],
      rarity: RARITY.RARE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Warsong Commander',
      description: '',
      stats: [3, 2, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: 'Arathi Weaponsmith',
      description: '',
      stats: [4, 3, 3],
      rarity: RARITY.COMMON,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [false, false, false, false, false, false, false],
    },
    {
      name: "Kor'kron Elite",
      description: '',
      stats: [4, 4, 3],
      rarity: RARITY.FREE,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
    {
      name: 'Grommash Hellscream',
      description: '',
      stats: [8, 4, 9],
      rarity: RARITY.LEGENDARY,
      tribe: TRIBE.NONE,
      overload: 0,
      attributes: [true, false, false, false, false, false, false],
    },
  ]

module.exports = {
  EFFECT_IDS,
  EFFECT_DATA,
}
