import { HeroClass, Rarity, Tribe, EffectType } from '../constants'

const EFFECT_DATA = [
  // effect objects will have more data than this
  // these are just the baseline values

  // DRUID
  {
    type: EffectType.SPELL,
    fileName: 'innervate', // for card displays on spells and "choose one"
    class: HeroClass.DRUID,
    name: 'Innervate',
    baseDescription: 'Gain 2 Mana Crystals this turn only.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0], // doesn't apply when not affected by spellpower
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'moonfire',
    class: HeroClass.DRUID,
    name: 'Moonfire',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'claw',
    class: HeroClass.DRUID,
    name: 'Claw',
    baseDescription: 'Give your hero +2 Attack this turn. Gain 2 Armor.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'naturalize',
    class: HeroClass.DRUID,
    name: 'Naturalize',
    baseDescription: 'Destroy a minion. Your opponent draws 2cards.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'savagery',
    class: HeroClass.DRUID,
    name: 'Savagery',
    baseDescription: "Deal damage equal to your hero's Attack to a minion.",
    rarity: Rarity.RARE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mark_of_the_wild',
    class: HeroClass.DRUID,
    name: 'Mark of the Wild',
    baseDescription:
      'Give a minion <b>Taunt</b> and +2/+2. <i>(+2 Attack/+2 Health)</i>',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'power_of_the_wild',
    class: HeroClass.DRUID,
    name: 'Power of the Wild',
    baseDescription:
      '<b>Choose One</b> - Give your minions +1/+1; or Summon a 3/2 Panther.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'power_of_the_wild_leader_of_the_pack',
    class: HeroClass.DRUID,
    name: 'Leader of the Pack',
    baseDescription: 'Give your minions +1/+1.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'power_of_the_wild_summon_a_panther',
    class: HeroClass.DRUID,
    name: 'Summon a Panther',
    baseDescription: 'Summon a 3/2 Panther.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'wild_growth',
    class: HeroClass.DRUID,
    name: 'Wild Growth',
    baseDescription: 'Gain an empty Mana Crystal.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'wrath',
    class: HeroClass.DRUID,
    name: 'Wrath',
    baseDescription:
      '<b>Choose One</b> - Deal {amount0} damage to a minion; or {amount1} damage and draw a card.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [3, 1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'wrath_natures_wrath',
    class: HeroClass.DRUID,
    name: "Nature's Wrath",
    baseDescription: 'Deal {amount0} damage to a minion. Draw a card.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'wrath_solar_wrath',
    class: HeroClass.DRUID,
    name: 'Solar Wrath',
    baseDescription: 'Deal {amount0} damage to a minion.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'healing_touch',
    class: HeroClass.DRUID,
    name: 'Healing Touch',
    baseDescription: 'Restore {amount0} Health.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [8],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'mark_of_nature',
    class: HeroClass.DRUID,
    name: 'Mark of Nature',
    baseDescription:
      '<b>Choose One</b> - Give a minion +4 Attack; or +4 Health and <b>Taunt</b>.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mark_of_nature_tigers_fury',
    class: HeroClass.DRUID,
    name: "Tiger's Fury",
    baseDescription: 'Give a minion +4 Attack.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mark_of_nature_thick_hide',
    class: HeroClass.DRUID,
    name: 'Thick Hide',
    baseDescription: 'Give a minion +4 Health and <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'savage_roar',
    class: HeroClass.DRUID,
    name: 'Savage Roar',
    baseDescription: 'Give your characters +2 Attack this turn.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'bite',
    class: HeroClass.DRUID,
    name: 'Bite',
    baseDescription: 'Give your hero +4 Attack this turn. Gain 4 Armor.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'soul_of_the_forest',
    class: HeroClass.DRUID,
    name: 'Soul of the Forest',
    baseDescription:
      'Give your minions "<b>Deathrattle<\b>: Summon a 2/2 Treant."',
    rarity: Rarity.COMMON,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'swipe',
    class: HeroClass.DRUID,
    name: 'Swipe',
    baseDescription:
      'Deal {amount0} damage to an enemy and {amount1} damage  to all other enemies.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [4, 1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'nourish',
    class: HeroClass.DRUID,
    name: 'Nourish',
    baseDescription:
      '<b>Choose One</b> - Gain 2 Mana Crystal; or Draw 3 cards.',
    rarity: Rarity.RARE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'nourish_enrich',
    class: HeroClass.DRUID,
    name: 'Enrich',
    baseDescription: 'Draw 3 cards.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'nourish_rampant_growth',
    class: HeroClass.DRUID,
    name: 'Rampant Growth',
    baseDescription: 'Gain 2 Mana Crystals.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'starfall',
    class: HeroClass.DRUID,
    name: 'Starfall',
    baseDescription:
      '<b>Choose One</b> - Deal {amount0} damage to a minion; or {amount1} damage to all enemy minions.',
    rarity: Rarity.RARE,
    cost: 5,
    amount: [5, 2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'starfall_starlord',
    class: HeroClass.DRUID,
    name: 'Starlord',
    baseDescription: 'Deal {amount0} damage to a minion.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'starfall_stellar_drift',
    class: HeroClass.DRUID,
    name: 'Stellar Drift',
    baseDescription: 'Deal {amount0} damage to all enemy minions.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.SPELL,
    fileName: 'force_of_nature',
    class: HeroClass.DRUID,
    name: 'Force of Nature',
    baseDescription:
      'Summon three 2/2 Treants with <b>Charge</b> that die at the end of the turn.',
    rarity: Rarity.EPIC,
    cost: 6,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'starfire',
    class: HeroClass.DRUID,
    name: 'Starfire',
    baseDescription: 'Deal {amount0} damage. Draw a card.',
    rarity: Rarity.FREE,
    cost: 6,
    amount: [5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  // HUNTER
  {
    type: EffectType.SPELL,
    fileName: 'hunters_mark',
    class: HeroClass.HUNTER,
    name: "Hunter's Mark",
    baseDescription: "Change a minion's Health to 1.",
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'arcane_shot',
    class: HeroClass.HUNTER,
    name: 'Arcane Shot',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'bestial_wrath',
    class: HeroClass.HUNTER,
    name: 'Bestial Wrath',
    baseDescription: 'Give a Beast +2 Attack and <b>Immune</b> this turn.',
    rarity: Rarity.EPIC,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'flare',
    class: HeroClass.HUNTER,
    name: 'Flare',
    baseDescription:
      'All minions lose <b>Stealth</b>.\nDestroy all enemy\n<b>Secrets</b>. Draw a card.',
    rarity: Rarity.RARE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'tracking',
    class: HeroClass.HUNTER,
    name: 'Tracking',
    baseDescription:
      'Look at the top 3 cards of your deck. Draw one and discard the others.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'explosive_trap',
    class: HeroClass.HUNTER,
    name: 'Explosive Trap',
    baseDescription:
      '<b>Secret</b>: When your hero is attacked, deal {amount0} damage to all enemies.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'freezing_trap',
    class: HeroClass.HUNTER,
    name: 'Freezing Trap',
    baseDescription:
      "<b>Secret</b>: When an enemy minion attacks, return it to its owner's hand. It costs (2) more.",
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'misdirection',
    class: HeroClass.HUNTER,
    name: 'Misdirection',
    baseDescription:
      '<b>Secret</b>: When an enemy attacks your hero, instead it attacks another random character.',
    rarity: Rarity.RARE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'snake_trap',
    class: HeroClass.HUNTER,
    name: 'Snake Trap',
    baseDescription:
      '<b>Secret</b>: When one of your minions is attacked, summon three 1/1 Snakes.',
    rarity: Rarity.EPIC,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'snipe',
    class: HeroClass.HUNTER,
    name: 'Snipe',
    baseDescription:
      '<b>Secret</b>: After your opponent plays a minion, deal {amount0} damage to it.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'animal_companion',
    class: HeroClass.HUNTER,
    name: 'Animal Companion',
    baseDescription: 'Summon a random Beast Companion.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'deadly_shot',
    class: HeroClass.HUNTER,
    name: 'Deadly Shot',
    baseDescription: 'Destroy a random enemy minion.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'kill_command',
    class: HeroClass.HUNTER,
    name: 'Kill Command',
    baseDescription:
      'Deal {amount0} damage. If you control a Beast, deal {amount1} damage instead.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [3, 5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'unleash_the_hounds',
    class: HeroClass.HUNTER,
    name: 'Unleash the Hounds',
    baseDescription:
      'For each enemy minion, summon a 1/1 Hound with <b>Charge</b>.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'multi_shot',
    class: HeroClass.HUNTER,
    name: 'Multi-Shot',
    baseDescription: 'Deal {amount0} damage to two random enemy  minions.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'explosive_shot',
    class: HeroClass.HUNTER,
    name: 'Explosive Shot',
    baseDescription:
      'Deal {amount0} damage to a minion and {amount1} damage to adjacent ones.',
    rarity: Rarity.RARE,
    cost: 5,
    amount: [5, 2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  // MAGE
  {
    type: EffectType.SPELL,
    fileName: 'arcane_missiles',
    class: HeroClass.MAGE,
    name: 'Arcane Missiles',
    baseDescription:
      'Deal {amount0} damage randomly split among all enemy characters.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'ice_lance',
    class: HeroClass.MAGE,
    name: 'Ice Lance',
    baseDescription:
      '<b>Freeze</b> a character. If it was already <b>Frozen</b>, deal {amount0} damage instead.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mirror_image',
    class: HeroClass.MAGE,
    name: 'Mirror Image',
    baseDescription: 'Summon two 0/2 minions with <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'arcane_explosion',
    class: HeroClass.MAGE,
    name: 'Arcane Explosion',
    baseDescription: 'Deal {amount0} to all enemy minions.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'frostbolt',
    class: HeroClass.MAGE,
    name: 'Frostbolt',
    baseDescription:
      'Deal {amount0} damage to a character and <b>Freeze</b> it.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'arcane_intellect',
    class: HeroClass.MAGE,
    name: 'Arcane Intellect',
    baseDescription: 'Draw 2 cards.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'counterspell',
    class: HeroClass.MAGE,
    name: 'Counterspell',
    baseDescription:
      '<b>Secret</b>: When your opponent casts a spell, <b>Counter</b> it.',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'frost_nova',
    class: HeroClass.MAGE,
    name: 'Frost Nova',
    baseDescription: '<b>Freeze</b> all enemy minions.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'ice_barrier',
    class: HeroClass.MAGE,
    name: 'Ice Barrier',
    baseDescription:
      '<b>Secret</b>: As soon as your hero is attacked, gain 8 armor.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'ice_block',
    class: HeroClass.MAGE,
    name: 'Ice Block',
    baseDescription:
      '<b>Secret</b>: When your hero takes fatal damage, prevent it and become <b>Immune</b> this turn.',
    rarity: Rarity.EPIC,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mirror_entity',
    class: HeroClass.MAGE,
    name: 'Mirror Entity',
    baseDescription:
      '<b>Secret</b>: When your opponent plays a minion, summon a copy of it.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'spellbender',
    class: HeroClass.MAGE,
    name: 'Spellbender',
    baseDescription:
      '<b>Secret</b>: When an enemy casts a spell on a minion, summon a 1/3 as the new target.',
    rarity: Rarity.EPIC,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'vaporize',
    class: HeroClass.MAGE,
    name: 'Vaporize',
    baseDescription:
      '<b>Secret</b>: When a minion attacks your hero, destroy it.',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'cone_of_cold',
    class: HeroClass.MAGE,
    name: 'Cone of Cold',
    baseDescription:
      '<b>Freeze</b> a minion and the minions next to it, and deal {amount0} damage to them.',
    rarity: Rarity.COMMON,
    cost: 4,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'fireball',
    class: HeroClass.MAGE,
    name: 'Fireball',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [6],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'polymorph',
    class: HeroClass.MAGE,
    name: 'Polymorph',
    baseDescription: 'Transform a minion into a 1/1 Sheep.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'blizzard',
    class: HeroClass.MAGE,
    name: 'Blizzard',
    baseDescription:
      'Deal {amount0} damage to all enemy minions and <b>Freeze</b> them.',
    rarity: Rarity.RARE,
    cost: 6,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'flamestrike',
    class: HeroClass.MAGE,
    name: 'Flamestrike',
    baseDescription: 'Deal {amount0} damage to all enemy minions.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'pyroblast',
    class: HeroClass.MAGE,
    name: 'Pyroblast',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.EPIC,
    cost: 10,
    amount: [10],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  // PALADIN
  {
    type: EffectType.SPELL,
    fileName: 'blessing_of_might',
    class: HeroClass.PALADIN,
    name: 'Blessing of Might',
    baseDescription: 'Give a minion +3 Attack.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'blessing_of_wisdom',
    class: HeroClass.PALADIN,
    name: 'Blessing of Wisdom',
    baseDescription: 'Choose a minion. Whenever it attacks, draw a card.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'eye_for_an_eye',
    class: HeroClass.PALADIN,
    name: 'Eye for an Eye',
    baseDescription:
      '<b>Secret</b>: When your hero takes damage, deal that much damage to the enemy hero.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'hand_of_protection',
    class: HeroClass.PALADIN,
    name: 'Hand of Protection',
    baseDescription: 'Give a minion <b>Divine Shield</b>.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'humility',
    class: HeroClass.PALADIN,
    name: 'Humility',
    baseDescription: "Change a minion's Attack to 1.",
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'noble_sacrifice',
    class: HeroClass.PALADIN,
    name: 'Noble Sacrifice',
    baseDescription:
      '<b>Secret</b>: When an enemy attacks, summon a 2/1 Defender as the new target.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'redemption',
    class: HeroClass.PALADIN,
    name: 'Redemption',
    baseDescription:
      '<b>Secret</b>: When a friendly minion dies, return it to life with 1 Health.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'repentance',
    class: HeroClass.PALADIN,
    name: 'Repentance',
    baseDescription:
      '<b>Secret</b>: After your opponent plays a minion, reduce its Health to 1.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'equality',
    class: HeroClass.PALADIN,
    name: 'Equality',
    baseDescription: 'Change the Health of ALL minions to 1.',
    rarity: Rarity.RARE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'holy_light',
    class: HeroClass.PALADIN,
    name: 'Holy Light',
    baseDescription: 'Restore {amount0} Health.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [6],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'divine_favor',
    class: HeroClass.PALADIN,
    name: 'Divine Favor',
    baseDescription:
      'Draw cards until you have as many in hand as your opponent.',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'blessing_of_kings',
    class: HeroClass.PALADIN,
    name: 'Blessing of Kings',
    baseDescription: 'Give a minion +4/+4. <i>(+4 Attack/+4 Health)</i>.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'consecration',
    class: HeroClass.PALADIN,
    name: 'Consecration',
    baseDescription: 'Deal {amount0} damage to all enemies.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'hammer_of_wrath',
    class: HeroClass.PALADIN,
    name: 'Hammer of Wrath',
    baseDescription: 'Deal {amount0} damage. Draw a card.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'blessed_champion',
    class: HeroClass.PALADIN,
    name: 'Blessed Champion',
    baseDescription: "Double a minion's Attack.",
    rarity: Rarity.RARE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'holy_wrath',
    class: HeroClass.PALADIN,
    name: 'Holy Wrath',
    baseDescription: 'Draw a card and deal damage equal to its Cost.',
    rarity: Rarity.RARE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'avenging_wrath',
    class: HeroClass.PALADIN,
    name: 'Avenging Wrath',
    baseDescription:
      'Deal {amount0} damage randomly split among all enemy characters.',
    rarity: Rarity.EPIC,
    cost: 6,
    amount: [8],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'lay_on_hands',
    class: HeroClass.PALADIN,
    name: 'Lay on Hands',
    baseDescription: 'Restore {amount0} Health. Draw 3 cards.',
    rarity: Rarity.EPIC,
    cost: 8,
    amount: [8],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  // PRIEST
  {
    type: EffectType.SPELL,
    fileName: 'circle_of_healing',
    class: HeroClass.PRIEST,
    name: 'Circle of Healing',
    baseDescription: 'Restore {amount0} Health to ALL minions.',
    rarity: Rarity.COMMON,
    cost: 0,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'silence',
    class: HeroClass.PRIEST,
    name: 'Silence',
    baseDescription: '<b>Silence</b> a minion.',
    rarity: Rarity.COMMON,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'holy_smite',
    class: HeroClass.PRIEST,
    name: 'Holy Smite',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'inner_fire',
    class: HeroClass.PRIEST,
    name: 'Inner Fire',
    baseDescription: "Change a minion's Attack to be equal to its Health.",
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mind_vision',
    class: HeroClass.PRIEST,
    name: 'Mind Vision',
    baseDescription:
      "Put a copy of a random card in your opponent's hand into your hand.",
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'power_word_shield',
    class: HeroClass.PRIEST,
    name: 'Power Word: Shield',
    baseDescription: 'Give a minion +2 Health. Draw a card.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'divine_spirit',
    class: HeroClass.PRIEST,
    name: 'Divine Spirit',
    baseDescription: "Double a minion's Health.",
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mind_blast',
    class: HeroClass.PRIEST,
    name: 'Mind Blast',
    baseDescription: 'Deal {amount0} damage to the enemy hero.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadow_word_pain',
    class: HeroClass.PRIEST,
    name: 'Shadow Word: Pain',
    baseDescription: 'Destroy a minion with 3 or less Attack.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadow_word_death',
    class: HeroClass.PRIEST,
    name: 'Shadow Word: Death',
    baseDescription: 'Destroy a minion with 5 or more Attack.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadowform',
    class: HeroClass.PRIEST,
    name: 'Shadowform',
    baseDescription:
      "Your Hero Power becomes 'Deal 2 damage.' If already in Shadowform: 3 damage.",
    rarity: Rarity.EPIC,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'thoughtsteal',
    class: HeroClass.PRIEST,
    name: 'Thoughtsteal',
    baseDescription:
      "Copy 2 cards in your opponent's deck and add them to your hand.",
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mass_dispel',
    class: HeroClass.PRIEST,
    name: 'Mass Dispel',
    baseDescription: '<b>Silence</b> all enemy minions. Draw a card.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mindgames',
    class: HeroClass.PRIEST,
    name: 'Mindgames',
    baseDescription:
      "Put a copy of a random minion from your opponent's deck into the battlefield.",
    rarity: Rarity.EPIC,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadow_madness',
    class: HeroClass.PRIEST,
    name: 'Shadow Madness',
    baseDescription:
      'Gain control of an enemy minion with 3 or less Attack until end of turn.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'holy_nova',
    class: HeroClass.PRIEST,
    name: 'Holy Nova',
    baseDescription:
      'Deal {amount0} damage to all enemies. Restore {amount1} Health to all friendly characters.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [2, 2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'holy_fire',
    class: HeroClass.PRIEST,
    name: 'Holy Fire',
    baseDescription:
      'Deal {amount0} damage. Restore {amount1} Health to your hero.',
    rarity: Rarity.RARE,
    cost: 6,
    amount: [5, 5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mind_control',
    class: HeroClass.PRIEST,
    name: 'Mind Control',
    baseDescription: 'Take control of an enemy minion.',
    rarity: Rarity.FREE,
    cost: 10,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  // ROGUE
  {
    type: EffectType.SPELL,
    fileName: 'backstab',
    class: HeroClass.ROGUE,
    name: 'Backstab',
    baseDescription: 'Deal {amount0} damage to an undamaged minion.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'preparation',
    class: HeroClass.ROGUE,
    name: 'Preparation',
    baseDescription: 'The nextspell you cast this turn costs (3) less.',
    rarity: Rarity.EPIC,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadowstep',
    class: HeroClass.ROGUE,
    name: 'Shadowstep',
    baseDescription:
      'Return a friendly minion to your hand. It costs (2) less.',
    rarity: Rarity.COMMON,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'cold_blood',
    class: HeroClass.ROGUE,
    name: 'Cold Blood',
    baseDescription:
      'Give a minion +2 Attack. <b>Combo</b>: +4 Attack instead.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'conceal',
    class: HeroClass.ROGUE,
    name: 'Conceal',
    baseDescription: 'Give your minions <b>Stealth</b> until your next turn.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'deadly_poison',
    class: HeroClass.ROGUE,
    name: 'Deadly Poison',
    baseDescription: 'Give your weapon +2 Attack.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'sinister_strike',
    class: HeroClass.ROGUE,
    name: 'Sinister Strike',
    baseDescription: 'Deal {amount0} damage to the enemy hero.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'betrayal',
    class: HeroClass.ROGUE,
    name: 'Betrayal',
    baseDescription:
      'Force an enemy minion to deal its damage to the minions next to it.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'blade_flurry',
    class: HeroClass.ROGUE,
    name: 'Blade Flurry',
    baseDescription: 'Destroy your weapon and deal its damage to all enemies.',
    rarity: Rarity.RARE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'eviscerate',
    class: HeroClass.ROGUE,
    name: 'Eviscerate',
    baseDescription:
      'Deal {amount0} damage. <b>Combo</b>: Deal {amount1} damage instead.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [2, 4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'sap',
    class: HeroClass.ROGUE,
    name: 'Sap',
    baseDescription: "Return an enemy minion to your opponent's hand.",
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shiv',
    class: HeroClass.ROGUE,
    name: 'Shiv',
    baseDescription: 'Deal {amount0} damage. Draw a card.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'fan_of_knives',
    class: HeroClass.ROGUE,
    name: 'Fan of Knives',
    baseDescription: 'Deal {amount0} damage to all enemy minions. Draw a card.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'headcrack',
    class: HeroClass.ROGUE,
    name: 'Headcrack',
    baseDescription:
      'Deal {amount0} damage to the enemy hero. <b>Combo</b>: Return this to your hand next turn.',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'assassinate',
    class: HeroClass.ROGUE,
    name: 'Assassinate',
    baseDescription: 'Destroy an enemy minion.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'vanish',
    class: HeroClass.ROGUE,
    name: 'Vanish',
    baseDescription: "Return all minions to their owner's hand.",
    rarity: Rarity.COMMON,
    cost: 6,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'sprint',
    class: HeroClass.ROGUE,
    name: 'Sprint',
    baseDescription: 'Draw 4 cards.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  // SHAMAN
  {
    type: EffectType.SPELL,
    fileName: 'ancestral_healing',
    class: HeroClass.SHAMAN,
    name: 'Ancestral Healing',
    baseDescription:
      'Restore a minion to full Health and give it <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'totemic_might',
    class: HeroClass.SHAMAN,
    name: 'Totemic Might',
    baseDescription: 'Give your Totems +2 Health.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'earth_shock',
    class: HeroClass.SHAMAN,
    name: 'Earth Shock',
    baseDescription:
      '<b>Silence</b> a minion, then deal {amount0} damage to it.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'forked_lightning',
    class: HeroClass.SHAMAN,
    name: 'Forked Lightning',
    baseDescription:
      'Deal {amount0} damage to 2 random enemy minions. <b>Overload</b>: ({overload})',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [2],
    affectedBySpellpower: true,
    overload: 2,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'frost_shock',
    class: HeroClass.SHAMAN,
    name: 'Frost Shock',
    baseDescription:
      'Deal {amount0} damage to an enemy character and <b>Freeze</b> it.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'lightning_bolt',
    class: HeroClass.SHAMAN,
    name: 'Lightning Bolt',
    baseDescription: 'Deal {amount0} damage. <b>Overload</b>: ({overload})',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [3],
    affectedBySpellpower: true,
    overload: 1,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'rockbiter_weapon',
    class: HeroClass.SHAMAN,
    name: 'Rockbiter Weapon',
    baseDescription: 'Give a friendly character +3 Attack this turn.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'ancestral_spirit',
    class: HeroClass.SHAMAN,
    name: 'Ancestral Spirit',
    baseDescription:
      'Choose a minion. When that minion is destroyed, return it to the battlefield.',
    rarity: Rarity.RARE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'windfury',
    class: HeroClass.SHAMAN,
    name: 'Windfury',
    baseDescription: 'Give a minion <b>Windfury</b>.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'far_sight',
    class: HeroClass.SHAMAN,
    name: 'Far Sight',
    baseDescription: 'Draw a card. That card costs (3) less.',
    rarity: Rarity.EPIC,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'feral_spirit',
    class: HeroClass.SHAMAN,
    name: 'Feral Spirit',
    baseDescription:
      'Summon two 2/3 Spirit Wolves with <b>Taunt</b>. <b>Overload</b>: ({overload})',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 2,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'hex',
    class: HeroClass.SHAMAN,
    name: 'Hex',
    baseDescription: 'Transform a minion into a 0/1 Frog with <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'lava_burst',
    class: HeroClass.SHAMAN,
    name: 'Lava Burst',
    baseDescription: 'Deal {amount0} damage. <b>Overload</b>: ({overload})',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [5],
    affectedBySpellpower: true,
    overload: 2,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'lightning_storm',
    class: HeroClass.SHAMAN,
    name: 'Lightning Storm',
    baseDescription:
      'Deal {amount0}-{amount1} damage to all enemy minions. <b>Overload</b>: ({overload})',
    rarity: Rarity.RARE,
    cost: 3,
    amount: [2, 3],
    affectedBySpellpower: true,
    overload: 2,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'bloodlust',
    class: HeroClass.SHAMAN,
    name: 'Bloodlust',
    baseDescription: 'Give your minions +3 Attack this turn.',
    rarity: Rarity.FREE,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  // WARLOCK
  {
    type: EffectType.SPELL,
    fileName: 'sacrificial_pact',
    class: HeroClass.WARLOCK,
    name: 'Sacrificial Pact',
    baseDescription: 'Destroy a Demon. Restore {amount0} Health to your hero.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [5],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'soulfire',
    class: HeroClass.WARLOCK,
    name: 'Soulfire',
    baseDescription: 'Deal {amount0} damage. Discard a random card.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'corruption',
    class: HeroClass.WARLOCK,
    name: 'Corruption',
    baseDescription:
      'Choose an enemy minion. At the start of your turn, destroy it.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mortal_coil',
    class: HeroClass.WARLOCK,
    name: 'Mortal Coil',
    baseDescription:
      'Deal {amount0} damage to a minion. If that kills it, draw a card.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'power_overwhelming',
    class: HeroClass.WARLOCK,
    name: 'Power Overwhelming',
    baseDescription:
      'Give a friendly minion +4/+4 until end of turn. Then, it dies. Horribly.',
    rarity: Rarity.COMMON,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'demonfire',
    class: HeroClass.WARLOCK,
    name: 'Demonfire',
    baseDescription:
      "Deal {amount0} damage to a minion. If it's a friendly Demon, give it +2/+2 instead.",
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'drain_life',
    class: HeroClass.WARLOCK,
    name: 'Drain Life',
    baseDescription:
      'Deal {amount0} damage. Restore {amount1} Health to your hero.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [2, 2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'sense_demons',
    class: HeroClass.WARLOCK,
    name: 'Sense Demons',
    baseDescription: 'Draw 2 Demons from your deck.',
    rarity: Rarity.COMMON,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadow_bolt',
    class: HeroClass.WARLOCK,
    name: 'Shadow Bolt',
    baseDescription: 'Deal {amount0} damage to a minion.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [4],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'hellfire',
    class: HeroClass.WARLOCK,
    name: 'Hellfire',
    baseDescription: 'Deal {amount0} damage to ALL characters.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shadowflame',
    class: HeroClass.WARLOCK,
    name: 'Shadowflame',
    baseDescription:
      'Destroy a friendly minion and deal its Attack damage to all enemy minions.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'bane_of_doom',
    class: HeroClass.WARLOCK,
    name: 'Bane of Doom',
    baseDescription:
      'Deal {amount0} damage to a character. If that kills it, summon a random Demon.',
    rarity: Rarity.EPIC,
    cost: 5,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'siphon_soul',
    class: HeroClass.WARLOCK,
    name: 'Siphon Soul',
    baseDescription: 'Destroy a minion. Restore {amount0} Health to your hero.',
    rarity: Rarity.RARE,
    cost: 6,
    amount: [3],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'twisting_nether',
    class: HeroClass.WARLOCK,
    name: 'Twisting Nether',
    baseDescription: 'Destroy all minions.',
    rarity: Rarity.EPIC,
    cost: 8,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  // WARRIOR
  {
    type: EffectType.SPELL,
    fileName: 'inner_rage',
    class: HeroClass.WARRIOR,
    name: 'Inner Rage',
    baseDescription: 'Deal {amount0} damage to a minion and give it +2 Attack.',
    rarity: Rarity.COMMON,
    cost: 0,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'execute',
    class: HeroClass.WARRIOR,
    name: 'Execute',
    baseDescription: 'Destroy a damaged enemy minion.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shield_slam',
    class: HeroClass.WARRIOR,
    name: 'Shield Slam',
    baseDescription: 'Deal 1 damage to a minion for each Armor you have.',
    rarity: Rarity.EPIC,
    cost: 1,
    amount: [0],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'upgrade',
    class: HeroClass.WARRIOR,
    name: 'Upgrade!',
    baseDescription:
      'If you have a weapon, give it +1/+1. Otherwise equip a 1/3 weapon.',
    rarity: Rarity.RARE,
    cost: 1,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'whirlwind',
    class: HeroClass.WARRIOR,
    name: 'Whirlwind',
    baseDescription: 'Deal {amount0} damage to ALL minions.',
    rarity: Rarity.FREE,
    cost: 1,
    amount: [1],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'battle_rage',
    class: HeroClass.WARRIOR,
    name: 'Battle Rage',
    baseDescription: 'Draw a card for each damaged friendly character.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'cleave',
    class: HeroClass.WARRIOR,
    name: 'Cleave',
    baseDescription: 'Deal {amount0} damage to two random enemy minions.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'commanding_shout',
    class: HeroClass.WARRIOR,
    name: 'Commanding Shout',
    baseDescription:
      "Your minions can't be reduced below 1 Health this turn. Draw a card.",
    rarity: Rarity.RARE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'heroic_strike',
    class: HeroClass.WARRIOR,
    name: 'Heroic Strike',
    baseDescription: 'Give your hero +4 Attack this turn.',
    rarity: Rarity.FREE,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'rampage',
    class: HeroClass.WARRIOR,
    name: 'Rampage',
    baseDescription: 'Give a damaged minion +3/+3.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'slam',
    class: HeroClass.WARRIOR,
    name: 'Slam',
    baseDescription:
      'Deal {amount0} damage to a minion. If it survives, draw a card.',
    rarity: Rarity.COMMON,
    cost: 2,
    amount: [2],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'charge',
    class: HeroClass.WARRIOR,
    name: 'Charge',
    baseDescription: 'Give a friendly minion +2 Attack and <b>Charge</b>.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [2],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'shield_block',
    class: HeroClass.WARRIOR,
    name: 'Shield Block',
    baseDescription: 'Gain 5 Armor. Draw a card.',
    rarity: Rarity.FREE,
    cost: 3,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'mortal_strike',
    class: HeroClass.WARRIOR,
    name: 'Mortal Strike',
    baseDescription:
      'Deal {amount0} damage. If you have 12 or less Health, deal {amount1} instead.',
    rarity: Rarity.RARE,
    cost: 4,
    amount: [4, 6],
    affectedBySpellpower: true,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: true,
  },
  {
    type: EffectType.SPELL,
    fileName: 'brawl',
    class: HeroClass.WARRIOR,
    name: 'Brawl',
    baseDescription: 'Destroy all minions except one. <i>(chosen randomly)</i>',
    rarity: Rarity.EPIC,
    cost: 5,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: true,
  },

  // OTHER

  // DRUID
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'keeper_of_the_grove_choose_one',
    class: HeroClass.DRUID,
    name: 'Choose One',
    baseDescription: '',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'keeper_of_the_grove_choose_one_dispel',
    class: HeroClass.DRUID,
    name: 'Dispel',
    baseDescription: '<b>Silence</b> a minion.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'keeper_of_the_grove_choose_one_moonfire',
    class: HeroClass.DRUID,
    name: 'Moonfire',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 4,
    amount: [2],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'druid_of_the_claw_choose_one',
    class: HeroClass.DRUID,
    name: 'Choose One',
    baseDescription: '',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'ancient_of_lore_choose_one',
    class: HeroClass.DRUID,
    name: 'Choose One',
    baseDescription: '',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'ancient_of_lore_choose_one_ancient_secrets',
    class: HeroClass.DRUID,
    name: 'Ancient Secrets',
    baseDescription: 'Restore {amount0} Health.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [7],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: true,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'ancient_of_lore_choose_one_ancient_teachings',
    class: HeroClass.DRUID,
    name: 'Ancient Teachings',
    baseDescription: 'Draw 2 cards.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'ancient_of_war_choose_one',
    class: HeroClass.DRUID,
    name: 'Choose One',
    baseDescription: '',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'ancient_of_war_choose_one_rooted',
    class: HeroClass.DRUID,
    name: 'Rooted',
    baseDescription: '+5 Health and <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'ancient_of_war_choose_one_uproot',
    class: HeroClass.DRUID,
    name: 'Uproot',
    baseDescription: '+5 Attack.',
    rarity: Rarity.FREE,
    cost: 7,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.CHOOSE_ONE,
    fileName: 'cenarius_choose_one',
    class: HeroClass.DRUID,
    name: 'Choose One',
    baseDescription: '',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'cenarius_choose_one_demigods_favor',
    class: HeroClass.DRUID,
    name: "Demigod's Favor",
    baseDescription: 'Give your other minions +2/+2.',
    rarity: Rarity.FREE,
    cost: 8,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.GENERIC,
    fileName: 'cenarius_choose_one_shandos_lesson',
    class: HeroClass.DRUID,
    name: "Shan'do's Lesson",
    baseDescription: 'Summon two 2/2 Treants with <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 8,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // HUNTER
  {
    type: EffectType.AURA,
    fileName: 'timber_wolf_aura',
    class: HeroClass.HUNTER,
    name: '+1 Attack',
    baseDescription: 'Your other Beasts have +1 Attack.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'houndmaster_battlecry',
    class: HeroClass.HUNTER,
    name: '+2/+2 and <b>Taunt</b>',
    baseDescription: 'Give a friendly Beast +2/+2 and <b>Taunt</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.AURA,
    fileName: 'tundra_rhino_aura',
    class: HeroClass.HUNTER,
    name: '<b>Charge</b>',
    baseDescription: 'Your Beasts have <b>Charge</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.DEATHRATTLE,
    fileName: 'savannah_highmane_deathrattle',
    class: HeroClass.HUNTER,
    name: '<b>Deathrattle</b>',
    baseDescription: 'Summon two 2/2 Hyenas.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // MAGE
  {
    type: EffectType.AURA,
    fileName: 'sorcerers_apprentice_aura',
    class: HeroClass.MAGE,
    name: 'Spells cost (1) less',
    baseDescription: 'Your spells cost (1) less.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'kirin_tor_mage_battlecry',
    class: HeroClass.MAGE,
    name: 'The next <b>Secret</b> you play this turn costs (0)',
    baseDescription: 'The next <b>Secret</b> you play this turn costs (0).',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // PALADIN
  {
    type: EffectType.BATTLECRY,
    fileName: 'argent_protector_battlecry',
    class: HeroClass.PALADIN,
    name: '',
    baseDescription: 'Give a friendly minion <b>Divine Shield</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'aldor_peacekeeper_battlecry',
    class: HeroClass.PALADIN,
    name: 'Aldor Peacekeeper',
    baseDescription: "Change an enemy minion's Attack to 1.",
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'guardian_of_kings_battlecry',
    class: HeroClass.PALADIN,
    name: '',
    baseDescription: 'Restore {amount0} Health to your hero.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [6],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.DEATHRATTLE,
    fileName: 'tirion_fordring_deathrattle',
    class: HeroClass.PALADIN,
    name: 'Equip a 5/3 Ashbringer',
    baseDescription: 'Equip a 5/3 Ashbringer.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // PRIEST
  {
    type: EffectType.AURA,
    fileName: 'auchenai_soulpriest_aura',
    class: HeroClass.PRIEST,
    name: 'Restoring Health deals damage instead',
    baseDescription:
      'Your cards and powers that restore Health now deal damage instead.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'cabal_shadow_priest_battlecry',
    class: HeroClass.PRIEST,
    name: '',
    baseDescription:
      'Take control of an enemy minion that has 2 or less Attack.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'temple_enforcer_battlecry',
    class: HeroClass.PRIEST,
    name: '+3 Health',
    baseDescription: 'Give a friendly minion +3 Health.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.AURA,
    fileName: 'prophet_velen_aura',
    class: HeroClass.PRIEST,
    name: 'Double damage and healing of spells and Hero Power',
    baseDescription:
      'Double the damage and healing of your spells and Hero Power.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // ROGUE
  {
    type: EffectType.COMBO,
    fileName: 'defias_ringleader_combo',
    class: HeroClass.ROGUE,
    name: '',
    baseDescription: 'Summon a 2/1 Defias Bandit.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.COMBO,
    fileName: 'edwin_vancleef_combo',
    class: HeroClass.ROGUE,
    name: '',
    baseDescription: 'Gain +2/+2 for each card played earlier this turn.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.COMBO,
    fileName: 'si7_agent_combo',
    class: HeroClass.ROGUE,
    name: '',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [2],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'master_of_disguise_battlecry',
    class: HeroClass.ROGUE,
    name: '<b>Stealth</b>',
    baseDescription: 'Give a friendly minion <b>Stealth</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.COMBO,
    fileName: 'kidnapper_combo',
    class: HeroClass.ROGUE,
    name: '',
    baseDescription: "Return a minion to its owner's hand.",
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  // SHAMAN
  {
    type: EffectType.AURA,
    fileName: 'flametongue_totem_aura',
    class: HeroClass.SHAMAN,
    name: '+2 Attack',
    baseDescription: 'Adjacent minions have +2 Attack.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'windspeaker_battlecry',
    class: HeroClass.SHAMAN,
    name: '<b>Windfury</b>',
    baseDescription: 'Give a friendly minion <b>Windfury</b>.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'fire_elemental_battlecry',
    class: HeroClass.SHAMAN,
    name: '',
    baseDescription: 'Deal {amount0} damage.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [3],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  // WARLOCK
  {
    type: EffectType.BATTLECRY,
    fileName: 'flame_imp_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Deal {amount0} damage to your hero.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [3],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'felstalker_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Discard a random card.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'felguard_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Destroy one of your Mana Crystals.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'void_terror_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription:
      'Destroy both adjacent minions and gain their Attack and Health.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'pit_lord_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Deal {amount0} damage to your hero.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [5],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.AURA,
    fileName: 'summoning_portal_aura',
    class: HeroClass.WARLOCK,
    name: 'Minions cost (2) less',
    baseDescription: 'Your minions cost (2) less, but not less than (1).',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'doomguard_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Discard two random cards.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'dread_infernal_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Deal {amount0} damage to ALL other characters.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [1],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'lord_jaraxxus_battlecry',
    class: HeroClass.WARLOCK,
    name: '',
    baseDescription: 'Destroy your hero and replace it with Lord Jaraxxus.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
  // WARRIOR
  {
    type: EffectType.BATTLECRY,
    fileName: 'cruel_taskmaster_battlecry',
    class: HeroClass.WARRIOR,
    name: '+2 Attack',
    baseDescription: 'Deal {amount0} damage to a minion and give it +2 Attack.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [1],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: true,
    requiresTarget: false,
    obtainable: false,
  },
  {
    type: EffectType.BATTLECRY,
    fileName: 'arathi_weaponsmith_battlecry',
    class: HeroClass.WARRIOR,
    name: '',
    baseDescription: 'Equip a 2/2 weapon.',
    rarity: Rarity.FREE,
    cost: 0,
    amount: [0],
    affectedBySpellpower: false,
    overload: 0,
    canTarget: false,
    requiresTarget: false,
    obtainable: false,
  },
]

export default EFFECT_DATA
