import { HeroClass, Rarity } from '@constants'

const HeroData = [
  {
    class: HeroClass.Druid,
    name: 'Malfurion Stormrage',
    fileName: 'malfurion_stormrage',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Hunter,
    name: 'Rexxar',
    fileName: 'rexxar',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Mage,
    name: 'Jaina Proudmoore',
    fileName: 'jaina_proudmoore',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Paladin,
    name: 'Uther Lightbringer',
    fileName: 'uther_lightbringer',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Priest,
    name: 'Anduin Wrynn',
    fileName: 'anduin_wrynn',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Rogue,
    name: 'Valeera_Sanguinar',
    fileName: 'valeera_sanguinar',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Shaman,
    name: 'Thrall',
    fileName: 'thrall',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Warlock,
    name: "Gul'dan",
    fileName: 'guldan',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  {
    class: HeroClass.Warrior,
    name: 'Garrosh Hellscream',
    fileName: 'garrosh_hellscream',
    mana: 0,
    attack: 0,
    health: 30,
    rarity: Rarity.Free,
  },
  // OTHER
  {
    class: HeroClass.Neutral,
    name: 'Hogger',
    fileName: 'hogger',
    mana: 0,
    attack: 0,
    health: 10,
    rarity: Rarity.Free,
  },
]

export default HeroData
